"use client";
import {useCallback,useEffect,useState} from 'react';
import {DialogFrame} from '../workspace-ui';
type Backup={userId:string;email:string;name:string;accountId?:string;accountName?:string;currentVersion?:number;weekKey?:string;sourceVersion?:number;completedAt?:string;state?:string;error?:string;attempts?:number};
type Archive={account_id:string;account_name:string;version:number;archived_at:string};
type Preview={userId:string;email:string;accountId:string;accountName:string;currentVersion:number;sourceVersion:number;completedAt:string;backupId:string;home:{fillCount:number;positionCount:number};cashActivityCount:number};
const date=(v?:string)=>v?new Date(v).toLocaleString('zh-TW',{hour12:false}):'—';
export function MemberBackupsPanel({sessionId}:{sessionId:string}) {
 const [rows,setRows]=useState<Backup[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[query,setQuery]=useState('');
 const [enabled,setEnabled]=useState(false),[events,setEvents]=useState<{created_at:string;before_version:number;after_version?:number;result:string}[]>([]);
 const [preview,setPreview]=useState<Preview|null>(null),[archives,setArchives]=useState<{member:Backup;items:Archive[]}|null>(null);
 const request=useCallback(async(url:string,body?:unknown)=>{const r=await fetch(url,{method:body?'POST':'GET',headers:{'x-workspace-session':sessionId,...(body?{'Content-Type':'application/json'}:{})},cache:'no-store',...(body?{body:JSON.stringify(body)}:{})});const data=await r.json();if(!r.ok)throw Error(data.error||'操作未完成');return data;},[sessionId]);
 const load=useCallback(async()=>{setLoading(true);try{const d=await request('/api/admin/member-backups');setRows(d.items);setEnabled(d.enabled);if(d.truncated)setMessage('目前顯示前 500 位會員。');}catch(e){setError((e as Error).message);}finally{setLoading(false);}},[request]);
 useEffect(()=>{const timer=setTimeout(()=>void load(),0);return ()=>clearTimeout(timer);},[load]);
 async function inspect(row:Backup){setBusy(true);setError('');try{setPreview(await request('/api/admin/member-backups?userId='+encodeURIComponent(row.userId)));const history=await request('/api/admin/member-backups?action=events&userId='+encodeURIComponent(row.userId));setEvents(history.events);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function restore(){if(!preview||busy)return;setBusy(true);setError('');try{await request('/api/admin/member-backups',{action:'restore',userId:preview.userId,backupId:preview.backupId,baseVersion:preview.currentVersion});setMessage(`${preview.email}：已還原為新版本`);setPreview(null);await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function showArchives(row:Backup){setBusy(true);setError('');try{const d=await request('/api/admin/member-backups?action=archives&userId='+encodeURIComponent(row.userId));setArchives({member:row,items:d.items});}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function download(row:Archive){setBusy(true);setError('');try{const r=await fetch(`/api/admin/member-backups?action=archive-download&userId=${encodeURIComponent(archives!.member.userId)}&accountId=${encodeURIComponent(row.account_id)}`,{headers:{'x-workspace-session':sessionId},cache:'no-store'});if(!r.ok)throw Error((await r.json()).error);const url=URL.createObjectURL(await r.blob()),a=document.createElement('a');a.href=url;a.download=`ledger-${row.account_id}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section className="panel" aria-label="會員每週備份"><header className="panel-head"><h2>會員每週備份</h2><button className="ghost" disabled={loading||busy} onClick={()=>void load()}>重新整理</button></header>{!enabled&&<p role="status">每週備份排程目前未啟用。</p>}<p>每週五紐約時間 16:00 備份已儲存的帳本，只保留最後成功版本。</p><label>搜尋會員<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="姓名或 email"/></label>{error&&<p role="alert" className="account-alert">{error}</p>}{message&&<p role="status">{message}</p>}
 {loading?<p role="status">正在載入…</p>:<ul className="ledger-list">{rows.filter(r=>`${r.email} ${r.name}`.toLowerCase().includes(query.toLowerCase())).map(row=><li key={row.userId}><div><strong>{row.name||row.email}</strong><small className="block">{row.email}</small><p>{row.completedAt?`最後成功備份 ${date(row.completedAt)} · v${row.sourceVersion}`:'尚無每週備份'}</p>{row.state&&row.state!=='SUCCESS'&&<p>{row.state==='FAILED'?'備份失敗，等待重試':row.state==='RUNNING'?'備份執行中':'等待備份'}{row.error&&`：${row.error}`}</p>}</div><div className="account-actions"><button className="ghost" disabled={busy||!row.completedAt} onClick={()=>void inspect(row)}>預覽還原</button><button className="ghost" disabled={busy} onClick={()=>void showArchives(row)}>封存帳本</button></div></li>)}</ul>}
 {preview&&<DialogFrame label="確認還原會員帳本" onClose={()=>!busy&&setPreview(null)}><section className="modal account-dialog"><h2>還原會員帳本</h2><p>{preview.email} · {preview.accountName}</p><p>以 {date(preview.completedAt)} 的備份（來源 v{preview.sourceVersion}）取代目前 v{preview.currentVersion} 的內容，儲存為新版本。</p><p>備份包含 {preview.home.fillCount} 筆成交、{preview.cashActivityCount} 筆資金活動、{preview.home.positionCount} 個持倉。備份後的修改將不在還原結果中。</p>{!!events.length&&<details><summary>最近還原紀錄</summary>{events.map((event,i)=><p key={i}>{date(event.created_at)} · v{event.before_version}{event.after_version?` → v${event.after_version}`:""} · {event.result==="SUCCESS"?"完成":event.result==="CONFLICT"?"版本衝突":"未完成"}</p>)}</details>}{error&&<p role="alert" className="account-alert">{error}</p>}<div className="account-actions"><button className="ghost" disabled={busy} onClick={()=>setPreview(null)}>取消</button><button className="primary" disabled={busy} onClick={()=>void restore()}>{busy?'還原中…':'確認還原'}</button></div></section></DialogFrame>}
 {archives&&<DialogFrame label="封存帳本" onClose={()=>!busy&&setArchives(null)}><section className="modal account-dialog"><h2>封存帳本</h2><p>{archives.member.email}</p>{!archives.items.length?<p>沒有封存帳本。</p>:<ul className="ledger-list">{archives.items.map(row=><li key={row.account_id}><span>{row.account_name} · v{row.version}</span><button className="ghost" disabled={busy} onClick={()=>void download(row)}>匯出 JSON</button></li>)}</ul>}{error&&<p role="alert">{error}</p>}<button className="ghost" disabled={busy} onClick={()=>setArchives(null)}>關閉</button></section></DialogFrame>}
 </section>;
}
