"use client";
import {useRef,useState} from 'react';
import {CASH_TYPES,cashDelta,validateCashActivity,validCashAmount} from '@/lib/cash-activities.mjs';
import {DialogFrame} from './workspace-ui';
import {InfoPopover} from './info-popover';
type Cash={id:string;type:string;amount:number;timestamp:string;accountId:string|null;currency:string|null;note?:string;requiresReview?:boolean;source?:string};
type Account={id:string;name:string;currency:string};
const localTime=(time:string)=>{const date=new Date(time);return new Date(date.getTime()-date.getTimezoneOffset()*60000).toISOString().slice(0,16);};
export function CashEditor({activity,accounts,onSave,onClose,now}:{activity?:Cash;accounts:Account[];onSave:(row:Cash)=>Promise<void>;onClose:()=>void;now?:string}){
 const [form,setForm]=useState(()=>({id:activity?.id||crypto.randomUUID(),type:activity?.type||'DEPOSIT',accountId:activity?.accountId||accounts[0]?.id||'',currency:activity?.currency||accounts[0]?.currency||'USD',amount:activity?String(activity.amount):'',timestamp:localTime(activity?.timestamp||now||new Date().toISOString()),note:activity?.note||'',source:activity?.source||'手動登錄'}));
 const [advanced,setAdvanced]=useState(activity?.type==='OPENING_BALANCE'),[error,setError]=useState(''),[busy,setBusy]=useState(false);const saving=useRef(false);
 const field=(key:keyof typeof form,value:string)=>setForm(current=>({...current,[key]:value}));
 const amountValid=validCashAmount(form.amount,form.type);
 const delta=amountValid?cashDelta({...form,amount:Number(form.amount)}):null;
 return <DialogFrame label={activity?'編輯資金活動':'新增資金'} onClose={()=>{if(!busy)onClose();}}><form className="modal cash-editor" onSubmit={async event=>{event.preventDefault();if(saving.current)return;saving.current=true;setBusy(true);setError('');try{const row=validateCashActivity(form,accounts);await onSave(row);onClose();}catch(cause){setError(cause instanceof Error?cause.message:'儲存失敗，輸入已保留');}finally{saving.current=false;setBusy(false);}}}>
 <header className="panel-head"><h2>{activity?'編輯資金活動':'新增資金'}</h2><button type="button" className="ghost" onClick={onClose} disabled={busy}>取消</button></header>
 <div className="cash-form-grid"><label>類型<select value={form.type} onChange={e=>field('type',e.target.value)}>{Object.entries(CASH_TYPES).filter(([key])=>advanced||key===form.type||key!=='OPENING_BALANCE').map(([key,label])=><option key={key} value={key}>{String(label)}</option>)}</select></label><label>交易帳戶<select required value={form.accountId} onChange={e=>field('accountId',e.target.value)}>{accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label>
 <label>幣別<select value={form.currency} onChange={e=>field('currency',e.target.value)}><option>USD</option><option>TWD</option></select></label><label>金額<input type="number" step="any" min={form.type==='OPENING_BALANCE'?undefined:0} inputMode="decimal" required aria-describedby="cash-amount-help" aria-invalid={form.amount!==''&&!amountValid} value={form.amount} onChange={e=>field('amount',e.target.value)}/><small id="cash-amount-help">{form.type==='OPENING_BALANCE'?'餘額校正可為零或負數':'請輸入大於 0 的金額，增減由類型決定'}</small></label><label className="cash-wide">發生時間（裝置當地時間）<input type="datetime-local" required value={form.timestamp} onChange={e=>field('timestamp',e.target.value)}/></label><label className="cash-wide">備註（選填）<input maxLength={2000} value={form.note} onChange={e=>field('note',e.target.value)}/></label></div>
 <details open={advanced} onToggle={e=>setAdvanced(e.currentTarget.open)}><summary>進階設定</summary><p>開啟後可選擇「期初餘額校正」；它會重設現金基準，並中斷當日連續績效，不能當作入金或獲利。</p></details>
 <p className="cash-preview">{form.type==='OPENING_BALANCE'?'校正後基準餘額':'本次現金增減'} <strong>{delta===null?'—':`${form.currency} ${delta>0?'+':''}${delta.toLocaleString('zh-TW',{maximumFractionDigits:2})}`}</strong></p>
 <small>入出金不計為報酬；股息、利息及稅費會影響績效。成交已登錄的手續費請勿重複填寫。</small>{error&&<p role="alert" className="account-alert">{error}</p>}
 <button className="primary" disabled={busy}>{busy?'儲存中…':'儲存資金活動'}</button></form></DialogFrame>;
}
export function CashLedger({activities,accounts,onAdd,onEdit,onDelete,onRestore}:{activities:Cash[];accounts:Account[];onAdd:()=>void;onEdit:(row:Cash)=>void;onDelete:(row:Cash)=>Promise<void>;onRestore:(row:Cash)=>Promise<void>}){
 const [undo,setUndo]=useState<Cash|null>(null),[pendingDelete,setPendingDelete]=useState<Cash|null>(null),[deleting,setDeleting]=useState(false),[error,setError]=useState('');const deletingRef=useRef(false);const names=Object.fromEntries(accounts.map(a=>[a.id,a.name]));
 return <section className="panel"><header className="panel-head"><h2>資金活動<InfoPopover label="資金活動"><p>入出金屬於本金移動；股息、利息、費用及稅款計入投資組合績效。交易閉環損益維持原本成交計算。</p></InfoPopover></h2><button className="primary" onClick={onAdd}>新增資金</button></header>
 {error&&<p role="alert" className="account-alert">{error}</p>}{pendingDelete&&<div className="cash-undo" role="group" aria-label="確認刪除資金活動"><p>刪除這筆 {CASH_TYPES[pendingDelete.type as keyof typeof CASH_TYPES]} {pendingDelete.currency} {pendingDelete.amount.toLocaleString()}？本頁可撤銷本次刪除。</p><button className="ghost" disabled={deleting} onClick={()=>setPendingDelete(null)}>取消刪除</button><button className="ghost danger" disabled={deleting} onClick={async()=>{if(deletingRef.current)return;deletingRef.current=true;setDeleting(true);try{await onDelete(pendingDelete);setUndo(pendingDelete);setPendingDelete(null);setError('');}catch(e){setError(e instanceof Error?e.message:'刪除失敗');}finally{deletingRef.current=false;setDeleting(false);}}}>確認刪除</button></div>}{undo&&<div className="cash-undo" role="status">已刪除 {CASH_TYPES[undo.type as keyof typeof CASH_TYPES]}<button className="ghost" onClick={async()=>{try{await onRestore(undo);setUndo(null);setError('');}catch(e){setError(e instanceof Error?e.message:'還原失敗');}}}>撤銷刪除</button></div>}
 {activities.length?<div className="table-wrap" tabIndex={0} role="region" aria-label="資金活動，可捲動"><table className="cash-table"><thead><tr><th>日期</th><th>類型</th><th>帳戶</th><th>金額</th><th>狀態</th><th>來源／備註</th><th>操作</th></tr></thead><tbody>{[...activities].sort((a,b)=>b.timestamp.localeCompare(a.timestamp)).map(row=><tr key={row.id}><td>{new Date(row.timestamp).toLocaleString('zh-TW',{hour12:false})}</td><td>{CASH_TYPES[row.type as keyof typeof CASH_TYPES]||row.type}</td><td>{row.accountId?names[row.accountId]||row.accountId:'待指定'}</td><td>{row.currency} {cashDelta(row).toLocaleString('zh-TW',{maximumFractionDigits:2})}</td><td>{row.requiresReview?'待確認':'已確認'}</td><td>{row.note||row.source||'—'}</td><td><button className="text-button" onClick={()=>onEdit(row)}>編輯</button><button className="text-button danger" onClick={()=>setPendingDelete(row)}>刪除</button></td></tr>)}</tbody></table></div>:<div className="empty"><p>尚無資金活動。先登錄入金，建立交易的資金基準。</p><button className="ghost" onClick={onAdd}>登錄第一筆資金</button></div>}</section>;
}
