/* eslint-disable @typescript-eslint/no-explicit-any */
"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { runSelfTests, STORAGE_KEY, summarize } from "@/lib/trade-engine.mjs";
import { QUOTE_REFRESH_MS, toProviderSymbol } from "@/lib/quote-engine.mjs";

type Fill = { id: string; accountId: string; symbol: string; market: string; currency: string; side: "BUY" | "SELL"; quantity: number; price: number; fee: number; timestamp: string; note?: string };
type Dataset = { version: string; profile: { name: string; baseCurrency: string; costMethod: string }; accounts: { id: string; name: string; currency: string }[]; fills: Fill[]; marketBars: Record<string, unknown>[]; settings: { quoteProvider: string } };
type Quote = { symbol: string; price: number; previousClose: number | null; changePct: number | null; currency: string; marketState: string; updatedAt: string; source: string };
const emptyData: Dataset = { version: "0.1.0", profile: { name: "我的交易帳本", baseCurrency: "USD", costMethod: "FIFO" }, accounts: [{ id: "main", name: "主要帳戶", currency: "USD" }], fills: [], marketBars: [], settings: { quoteProvider: "json" } };
const demoData: Dataset = { ...emptyData, fills: [
  { id: "nvts-buy", accountId: "main", symbol: "NVTS", market: "NASDAQ", currency: "USD", side: "BUY", quantity: 100, price: 10, fee: 1, timestamp: "2026-07-01T09:30:00Z", note: "示範資料" },
  { id: "nvts-sell", accountId: "main", symbol: "NVTS", market: "NASDAQ", currency: "USD", side: "SELL", quantity: 100, price: 12.5, fee: 1, timestamp: "2026-07-10T09:30:00Z" },
  { id: "wday-buy", accountId: "main", symbol: "WDAY", market: "NASDAQ", currency: "USD", side: "BUY", quantity: 20, price: 200, fee: 1, timestamp: "2026-08-01T09:30:00Z" },
], marketBars: [{ symbol: "NVTS", date: "2026-07-02", open: 10, high: 11, low: 9, close: 10.7 }, { symbol: "NVTS", date: "2026-07-08", open: 11, high: 13.2, low: 10.5, close: 12.8 }, { symbol: "WDAY", date: "2026-08-04", open: 201, high: 210, low: 196, close: 205 }] };
function pct(value: number | null) { return value == null ? "—" : `${value >= 0 ? "+" : ""}${(value * 100).toFixed(1)}%`; }
function money(value: number, currency = "USD") { return new Intl.NumberFormat("zh-TW", { style: "currency", currency, maximumFractionDigits: 2 }).format(value); }
function moneyByCurrency(values: Record<string, number>) { const rows = Object.entries(values); return rows.length ? rows.map(([currency, value]) => money(value, currency)).join(" · ") : money(0); }

export default function Home() {
  const [data, setData] = useState<Dataset>(() => { if (typeof window !== "undefined") { const saved = localStorage.getItem(STORAGE_KEY); if (saved) { try { return JSON.parse(saved); } catch (error) { console.warn("無法恢復本機交易資料", error); } } } return demoData; }); const [tab, setTab] = useState("overview"); const [message, setMessage] = useState("資料已從本機或示範檔載入；可匯入自己的 JSON 覆蓋。 "); const [dialog, setDialog] = useState(false); const inputRef = useRef<HTMLInputElement>(null);
  const [form, setForm] = useState<Fill>({ id: "", accountId: "main", symbol: "", market: "NASDAQ", currency: "USD", side: "BUY", quantity: 1, price: 0, fee: 0, timestamp: new Date().toISOString().slice(0, 16), note: "" });
  useEffect(() => { localStorage.setItem(STORAGE_KEY, JSON.stringify(data)); }, [data]);
  const report = useMemo(() => summarize(data), [data]); const tests = useMemo(() => runSelfTests(), []);
  const [quotes, setQuotes] = useState<Record<string, Quote>>({}); const [quoteState, setQuoteState] = useState("準備更新"); const [lastQuoteAt, setLastQuoteAt] = useState<number | null>(null); const [clock, setClock] = useState(0);
  const quoteTargets = useMemo(() => report.positions.map((position: any) => toProviderSymbol(position.symbol, position.market)), [report.positions]);
  const quoteKey = quoteTargets.join(",");
  useEffect(() => { const ticker = window.setInterval(() => setClock(Date.now()), 1000); return () => window.clearInterval(ticker); }, []);
  useEffect(() => {
    if (!quoteKey) return;
    let active = true;
    const refresh = async () => {
      try { const response = await fetch(`/api/quotes?symbols=${encodeURIComponent(quoteKey)}`, { cache: "no-store" }); if (!response.ok) throw new Error(`HTTP ${response.status}`); const payload = await response.json(); if (!active) return; setQuotes(Object.fromEntries(payload.quotes.map((quote: Quote) => [quote.symbol, quote]))); setLastQuoteAt(Date.now()); setQuoteState(payload.errors?.length ? `${payload.errors.length} 個標的更新失敗` : "即時報價已更新"); }
      catch (error) { if (active) setQuoteState(`更新失敗：${error instanceof Error ? error.message : "未知錯誤"}`); }
    };
    refresh(); const timer = window.setInterval(refresh, QUOTE_REFRESH_MS); return () => { active = false; window.clearInterval(timer); };
  }, [quoteKey]);
  const nextRefresh = lastQuoteAt == null ? 0 : Math.max(0, Math.ceil((QUOTE_REFRESH_MS - (clock - lastQuoteAt)) / 1000));
  const displayedQuoteState = quoteKey ? quoteState : "沒有待更新持倉";
  function importJson(file?: File) { if (!file) return; file.text().then((text) => { try { const parsed = JSON.parse(text); const checked = summarize(parsed); if (checked.issues.some((i: any) => i.level === "error")) throw new Error(checked.issues.filter((i: any) => i.level === "error").map((i: any) => i.message).join("；")); setData(parsed); setMessage(`已匯入 ${parsed.fills.length} 筆成交。`); } catch (error: any) { setMessage(`匯入失敗：${error.message}`); } }); }
  function exportJson() { const url = URL.createObjectURL(new Blob([JSON.stringify(data, null, 2)], { type: "application/json" })); const a = document.createElement("a"); a.href = url; a.download = `trade-review-${new Date().toISOString().slice(0, 10)}.json`; a.click(); URL.revokeObjectURL(url); setMessage("JSON 備份已下載。 "); }
  function addFill(event: React.FormEvent) { event.preventDefault(); const fill = { ...form, id: form.id || `fill-${Date.now()}`, symbol: form.symbol.toUpperCase(), timestamp: new Date(form.timestamp).toISOString(), quantity: Number(form.quantity), price: Number(form.price), fee: Number(form.fee) }; setData({ ...data, fills: [...data.fills, fill] }); setDialog(false); setMessage(`已新增 ${fill.symbol} ${fill.side === "BUY" ? "買進" : "賣出"}紀錄。`); }
  function deleteFill(id: string) { setData({ ...data, fills: data.fills.filter((fill) => fill.id !== id) }); setMessage("成交紀錄已刪除。 "); }
  const metrics = [["成交紀錄", data.fills.length, `${report.issues.length} 項資料提醒`], ["完整閉環", report.cycles.length, `${report.positions.length} 個未平倉部位`], ["已實現損益", moneyByCurrency(report.realizedPnlByCurrency), "依幣別分列・FIFO・含手續費"], ["測試結果", `${tests.filter((t: any) => t.passed).length}/${tests.length}`, tests.every((t: any) => t.passed) ? "目前全部通過" : "需要修正"]];
  return <main className="shell">
    <aside className="sidebar"><div className="brand"><span>TR</span><strong>交易復盤顧問</strong></div><nav aria-label="主要導覽">{[["overview","總覽"],["trades","成交資料"],["cycles","交易閉環"],["tests","測試中心"]].map(([key,label]) => <button key={key} className={tab === key ? "active" : ""} onClick={() => setTab(key)}>{label}</button>)}</nav><div className="provider"><span>行情來源</span><b>{data.settings?.quoteProvider === "tradingview-mcp" ? "TradingView MCP" : "JSON 日線"}</b><small>MCP 適配器已預留，離線測試不受影響</small></div><div className="local-note">個人資料只保存在此瀏覽器<br/><b>本機 JSON 模式</b></div></aside>
    <section className="content"><header className="topbar"><div><p className="eyebrow">PHASE 0 · LOCAL FIRST</p><h1>{tab === "overview" ? "交易資料工作台" : tab === "trades" ? "成交資料" : tab === "cycles" ? "交易閉環" : "測試中心"}</h1></div><div className="actions"><input ref={inputRef} hidden type="file" accept="application/json" onChange={(e) => importJson(e.target.files?.[0])}/><button className="ghost" onClick={() => inputRef.current?.click()}>匯入 JSON</button><button className="ghost" onClick={exportJson}>匯出備份</button><button className="primary" onClick={() => setDialog(true)}>新增交易</button></div></header>
      <div className="notice"><span>●</span><div><b>{report.issues.some((i: any) => i.level === "error") ? "資料需要處理" : "資料計算完成"}</b><p>{message}</p></div></div>
      {tab === "overview" && <><section className="quote-bar"><div><span className="live-dot"/> <b>即時持倉報價</b><small>{displayedQuoteState}</small></div><div><b>{lastQuoteAt ? new Date(lastQuoteAt).toLocaleTimeString("zh-TW") : "—"}</b><small>{lastQuoteAt ? `${nextRefresh} 秒後更新` : quoteKey ? "正在取得報價" : "沒有待更新標的"}</small></div></section><section className="metrics">{metrics.map(([label,value,hint]) => <article key={String(label)}><span>{label}</span><strong>{value}</strong><small>{hint}</small></article>)}</section><CycleTable cycles={report.cycles} title="最近交易閉環"/><section className="split"><article className="panel"><p className="eyebrow">OPEN POSITIONS</p><h2>目前持倉</h2>{report.positions.length ? report.positions.map((p: any) => { const providerSymbol = toProviderSymbol(p.symbol,p.market); const quote = quotes[providerSymbol]; const direction = p.direction === "SHORT" ? -1 : 1; const unrealized = quote ? (quote.price - p.averageCost) * p.quantity * direction : null; return <div className="position live" key={p.symbol}><div><b>{p.symbol} <span className={`direction ${p.direction.toLowerCase()}`}>{p.direction === "SHORT" ? "空" : "多"}</span></b><small>{p.quantity} 股・均價 {money(p.averageCost,p.currency)}</small></div><div><b>{quote ? money(quote.price,quote.currency) : "更新中"}</b><small className={quote?.changePct != null && quote.changePct >= 0 ? "positive" : "negative"}>{quote?.changePct == null ? "—" : pct(quote.changePct)}</small></div><div><b className={unrealized != null && unrealized >= 0 ? "positive" : "negative"}>{unrealized == null ? "—" : money(unrealized,quote.currency)}</b><small>未實現損益</small></div></div> }) : <Empty text="目前沒有未平倉部位"/>}</article><article className="panel"><p className="eyebrow">DATA HEALTH</p><h2>資料品質</h2><div className="quality"><strong>{report.qualityPct}%</strong><div><span style={{width:`${report.qualityPct}%`}}/></div><small>具備持倉期間日線行情的閉環比例</small></div></article></section></>}
      {tab === "trades" && <section className="panel"><div className="panel-head"><div><p className="eyebrow">LEDGER</p><h2>個人成交帳本</h2></div><span className="muted">依成交時間排序</span></div><div className="table-wrap"><table><thead><tr><th>日期</th><th>標的</th><th>方向</th><th>數量</th><th>價格</th><th>費用</th><th></th></tr></thead><tbody>{[...data.fills].sort((a,b) => b.timestamp.localeCompare(a.timestamp)).map(fill => <tr key={fill.id}><td>{fill.timestamp.slice(0,10)}</td><td><b>{fill.symbol}</b><small className="block">{fill.market}</small></td><td><span className={`side ${fill.side.toLowerCase()}`}>{fill.side === "BUY" ? "買進" : "賣出"}</span></td><td>{fill.quantity}</td><td>{money(fill.price,fill.currency)}</td><td>{money(fill.fee,fill.currency)}</td><td><button className="danger" onClick={() => deleteFill(fill.id)}>刪除</button></td></tr>)}</tbody></table></div></section>}
      {tab === "cycles" && <CycleTable cycles={report.cycles} title="全部交易閉環"/>}
      {tab === "tests" && <section className="split tests"><article className="panel"><p className="eyebrow">AUTOMATED TESTS</p><h2>核心計算測試</h2><div className="test-list">{tests.map((test: any) => <div key={test.name}><span className={test.passed ? "pass" : "fail"}>{test.passed ? "✓" : "!"}</span><b>{test.name}</b><small>{test.detail || "通過"}</small></div>)}</div></article><article className="panel"><p className="eyebrow">VALIDATION</p><h2>目前資料檢查</h2>{report.issues.length ? <div className="test-list">{report.issues.map((issue: any,index: number) => <div key={`${issue.code}-${index}`}><span className={issue.level === "error" ? "fail" : "warn-dot"}>!</span><b>{issue.code}</b><small>{issue.message}</small></div>)}</div> : <Empty text="沒有發現資料問題"/>}</article></section>}
    </section>
    {dialog && <div className="overlay" role="dialog" aria-modal="true"><form className="modal" onSubmit={addFill}><div className="panel-head"><div><p className="eyebrow">NEW FILL</p><h2>新增成交</h2></div><button type="button" className="close" onClick={() => setDialog(false)}>×</button></div><div className="form-grid"><label>股票代號<input required value={form.symbol} onChange={e => setForm({...form,symbol:e.target.value})}/></label><label>方向<select value={form.side} onChange={e => setForm({...form,side:e.target.value as "BUY"|"SELL"})}><option value="BUY">買進</option><option value="SELL">賣出</option></select></label><label>數量<input required min="0.0001" step="any" type="number" value={form.quantity} onChange={e => setForm({...form,quantity:Number(e.target.value)})}/></label><label>成交價<input required min="0.0001" step="any" type="number" value={form.price} onChange={e => setForm({...form,price:Number(e.target.value)})}/></label><label>手續費<input min="0" step="any" type="number" value={form.fee} onChange={e => setForm({...form,fee:Number(e.target.value)})}/></label><label>成交時間<input required type="datetime-local" value={form.timestamp} onChange={e => setForm({...form,timestamp:e.target.value})}/></label><label className="wide">備註<input value={form.note} onChange={e => setForm({...form,note:e.target.value})}/></label></div><div className="modal-actions"><button type="button" className="ghost" onClick={() => setDialog(false)}>取消</button><button className="primary">儲存成交</button></div></form></div>}
  </main>;
}
function CycleTable({cycles,title}: {cycles:any[];title:string}) { return <section className="panel"><div className="panel-head"><div><p className="eyebrow">CLOSED CYCLES</p><h2>{title}</h2></div><span className="muted">FIFO・多空雙向・日曆日</span></div>{cycles.length ? <div className="table-wrap"><table><thead><tr><th>標的</th><th>方向</th><th>期間</th><th>持倉</th><th>損益</th><th>報酬</th><th>MAE</th><th>MFE</th><th>行情</th></tr></thead><tbody>{cycles.map(c => <tr key={c.id}><td><b>{c.symbol}</b></td><td><span className={`direction ${c.direction.toLowerCase()}`}>{c.direction === "SHORT" ? "空" : "多"}</span></td><td>{c.openAt.slice(0,10)} → {c.closeAt.slice(0,10)}</td><td>{c.holdingDays} 天</td><td className={c.pnl >= 0 ? "positive" : "negative"}>{money(c.pnl,c.currency)}</td><td>{pct(c.returnPct)}</td><td>{pct(c.maePct)}</td><td>{pct(c.mfePct)}</td><td><span className={c.quality === "完整" ? "status ok" : "status warn"}>{c.quality}</span></td></tr>)}</tbody></table></div> : <Empty text="尚未形成完整交易閉環"/>}</section> }
function Empty({text}: {text:string}) { return <div className="empty"><span>○</span><p>{text}</p></div> }
