"use client";
import {useValuation} from './valuation-context';
import {FitNumber} from "./mobile-ui";
import {useWorkspaceClock} from './workspace-clock';
import {useEffect,useMemo,useRef,useState,useSyncExternalStore} from 'react';
import {buildPerformanceDaily,performanceRange} from '@/lib/performance-engine.mjs';
import type {PerformanceResource} from "./performance-preload";
import {InfoPopover,InfoPopoverGroup} from './info-popover';
type Series='portfolio'|'QQQ'|'SPY';
type Point={date:string;total:number|null;flow:number;rate:number|null;reset:boolean;portfolio:number|null;drawdown:number|null;returns:Record<'QQQ'|'SPY',number|null>;drawdowns:Record<'QQQ'|'SPY',number|null>;issues:string[];problems:string[];warnings:string[];benchmarkProblems:Record<string,string[]>;quoteDates:Record<string,string>};
type Month={month:string;portfolio:number|null;QQQ:number|null;SPY:number|null;partial:boolean};
type Range={points:Point[];months:Month[];summary:Record<Series|'maxDrawdown',number|null>;start:string;end:string};
const names={portfolio:'投資組合',QQQ:'QQQ',SPY:'SPY'};
const colors={portfolio:'var(--green)',QQQ:'#397ee6',SPY:'#c77e19'};
const keys:Series[]=['portfolio','QQQ','SPY'];
const percent=(v:number|null)=>v==null?'—':`${v>0?'+':''}${(v*100).toFixed(1)}%`;
const difference=(a:number|null,b:number|null)=>a==null||b==null?'—':`${a-b>=0?'+':''}${((a-b)*100).toFixed(1)} 百分點`;
function useWidth(){const ref=useRef<HTMLDivElement>(null);const [width,setWidth]=useState(900);useEffect(()=>{if(!ref.current)return;const observer=new ResizeObserver(([entry])=>setWidth(Math.max(280,entry.contentRect.width)));observer.observe(ref.current);return()=>observer.disconnect();},[]);return {ref,width};}
function PerformanceChart({points,visible,drawdown=false,selected,onSelect,onZoom}:{points:Point[];visible:Series[];drawdown?:boolean;selected:number|null;onSelect:(i:number|null)=>void;onZoom:(a:string,b:string)=>void}){
 const suppressClick=useRef(false);const {ref,width}=useWidth();const [drag,setDrag]=useState<{from:number;to:number}|null>(null);const height=drawdown?180:310,left=58,right=20,top=20,bottom=36;
 const value=(p:Point,key:Series)=>key==='portfolio'?(drawdown?p.drawdown:p.portfolio):(drawdown?p.drawdowns[key]:p.returns[key]);
 const values=points.flatMap(p=>visible.map(k=>value(p,k))).filter((v):v is number=>v!=null&&Number.isFinite(v));
 const low=Math.min(0,...values),high=Math.max(0,...values),pad=Math.max(.01,(high-low)*.12),min=low-pad,max=drawdown?0:high+pad;
 const x=(i:number)=>left+(width-left-right)*i/Math.max(1,points.length-1),y=(v:number)=>top+(max-v)/(max-min)*(height-top-bottom);
 const indexAt=(client:number,svg:SVGSVGElement)=>Math.max(0,Math.min(points.length-1,Math.round(((client-svg.getBoundingClientRect().left)/svg.getBoundingClientRect().width*width-left)/(width-left-right)*Math.max(1,points.length-1))));
 const ticks=Array.from({length:5},(_,i)=>min+(max-min)*i/4),dates=[...new Set(Array.from({length:width<500?3:6},(_,i)=>Math.round((points.length-1)*i/(width<500?2:5))))];
 const path=(key:Series)=>{let result='',connected=false;points.forEach((p,i)=>{const v=value(p,key);if(v==null){connected=false;return;}result+=`${connected?'L':'M'}${x(i)},${y(v)} `;connected=true;});return result;};
 return <div className="performance-plot" ref={ref}><svg viewBox={`0 0 ${width} ${height}`} style={{height}} tabIndex={0} role="group" aria-label={drawdown?'回撤圖，左右鍵逐日查看':'累積報酬圖，左右鍵逐日查看，滑鼠拖選期間'} onKeyDown={e=>{if(e.key==='Escape'){setDrag(null);onSelect(null);}else if(['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();onSelect(Math.max(0,Math.min(points.length-1,(selected??(e.key==='ArrowLeft'?points.length: -1))+(e.key==='ArrowLeft'?-1:1))));}}}
 onPointerMove={e=>{if(e.pointerType==='touch')return;const i=indexAt(e.clientX,e.currentTarget);onSelect(i);if(drag)setDrag({...drag,to:i});}}
 onPointerLeave={()=>{if(!drag)onSelect(null);}}
 onPointerDown={e=>{if(e.pointerType!=='mouse'||e.button!==0||drawdown)return;const i=indexAt(e.clientX,e.currentTarget);setDrag({from:i,to:i});e.currentTarget.setPointerCapture(e.pointerId);}}
 onPointerUp={e=>{const i=indexAt(e.clientX,e.currentTarget);if(e.pointerType==='touch'){return;}onSelect(i);if(drag&&Math.abs(drag.to-drag.from)>1){suppressClick.current=true;onZoom(points[Math.min(drag.from,drag.to)].date,points[Math.max(drag.from,drag.to)].date);}setDrag(null);}}
 onClick={e=>{if(suppressClick.current){suppressClick.current=false;return;}onSelect(indexAt(e.clientX,e.currentTarget));}} onPointerCancel={()=>setDrag(null)}>
 {ticks.map(v=><g key={v}><line x1={left} x2={width-right} y1={y(v)} y2={y(v)} className="performance-grid-line"/><text x={left-8} y={y(v)+4} textAnchor="end">{(v*100).toFixed(1)}%</text></g>)}
 <line x1={left} x2={width-right} y1={y(0)} y2={y(0)} className="performance-zero"/>
 {dates.map(i=><text key={i} x={x(i)} y={height-10} textAnchor={i===0?'start':i===points.length-1?'end':'middle'}>{points[i]?.date}</text>)}
 {visible.map(key=><path key={key} d={path(key)} fill="none" stroke={colors[key]} strokeWidth={key==='portfolio'?2.8:1.8} strokeDasharray={key==='QQQ'?'7 3':key==='SPY'?'2 3':undefined}/>)}
 {drag&&<rect x={x(Math.min(drag.from,drag.to))} y={top} width={Math.abs(x(drag.to)-x(drag.from))} height={height-top-bottom} fill="var(--green)" opacity=".12"/>}
 {selected!=null&&points[selected]&&<g><line x1={x(selected)} x2={x(selected)} y1={top} y2={height-bottom} stroke="var(--muted)" strokeDasharray="3 3"/>{visible.map(k=>{const v=value(points[selected],k);return v==null?null:<circle key={k} cx={x(selected)} cy={y(v)} r="3.5" fill={colors[k]}/>;})}</g>}
 </svg>{!values.length&&<div className="performance-no-chart">{visible.length?'這段期間缺少有效資料，請查看資料狀態。':'請至少開啟一個系列。'}</div>}</div>;
}
function MonthChart({months,visible}:{months:Month[];visible:Series[]}){
 const {ref,width:containerWidth}=useWidth();const width=Math.max(containerWidth,500,months.length*76),height=230,left=50,top=22,bottom=42,plot=height-top-bottom;
 const values=months.flatMap(m=>visible.map(k=>m[k])).filter((v):v is number=>v!=null);const lo=Math.min(0,...values),hi=Math.max(.01,...values),pad=(hi-lo)*.12,min=lo-pad,max=hi+pad,y=(v:number)=>top+(max-v)/(max-min)*plot;
 const [hint,setHint]=useState('');
 return <div className="performance-month-chart" ref={ref}><div className="performance-month-hint" role="status">{hint||'指向長條查看各月數值；＊為部分期間'}</div><div className="performance-month-scroll" tabIndex={0} role="region" aria-label="月度報酬圖，可左右捲動"><svg width={width} height={height} role="group" aria-label="月度報酬比較" onPointerLeave={()=>setHint('')} onKeyDown={e=>{if(e.key==='Escape')setHint('');}}>
 {[min,0,max].map(v=><g key={v}><line x1={left} x2={width-12} y1={y(v)} y2={y(v)} className={v===0?'performance-zero':'performance-grid-line'}/><text x={left-5} y={y(v)+4} textAnchor="end">{(v*100).toFixed(1)}%</text></g>)}
 {months.map((m,i)=>{const center=left+(width-left-12)*(i+.5)/months.length;return <g key={m.month}>{visible.map((k,j)=>{const v=m[k],x=center+(j-(visible.length-1)/2)*17-7,label=`${m.month}${m.partial?'（部分期間）':''} ${names[k]} ${v==null?'資料不足':percent(v)}`;return <g key={k} tabIndex={0} aria-label={label} onFocus={()=>setHint(label)} onBlur={()=>setHint('')} onPointerEnter={()=>setHint(label)} onClick={()=>setHint(label)}><rect x={x} y={top} width="15" height={plot} fill="transparent"/>{v==null?<text x={x+7} y={y(0)-3} textAnchor="middle">—</text>:<rect x={x} y={Math.min(y(0),y(v))} width="14" height={Math.max(1,Math.abs(y(v)-y(0)))} fill={colors[k]}/>}</g>;})}<text x={center} y={height-18} textAnchor="middle">{m.month.slice(2)}{m.partial?'＊':''}</text></g>;})}</svg></div></div>;
}
export function PerformanceWorkspace({data,resource}:{data:object;resource:PerformanceResource}){
 const {currency,format:dollars}=useValuation();
 const clock=useWorkspaceClock();const asOf=useMemo(()=>new Date(clock),[clock]);
 const sourceKey=JSON.stringify(data);const source=useMemo(()=>JSON.parse(sourceKey),[sourceKey]);
 const {history,status,loading}=useSyncExternalStore(resource.subscribe,resource.getSnapshot,resource.getSnapshot);
 const [dataOpen,setDataOpen]=useState(false),[dataPage,setDataPage]=useState(0);
 const [scope,setScope]=useState('all'),[custom,setCustom]=useState({start:'',end:''}),[selected,setSelected]=useState<number|null>(null),[visible,setVisible]=useState<Series[]>(keys),[ddEtfs,setDdEtfs]=useState(false),[year,setYear]=useState('recent');
 const daily=useMemo(()=>buildPerformanceDaily(source,history?.cache,asOf,currency),[source,history,asOf,currency]);
 const bounds=useMemo(()=>{const end=daily.end;let start=daily.start||end;if(scope==='custom')return {start:custom.start||start,end:custom.end||end};if(scope==='ytd')start=end.slice(0,4)+'-01-01';if(scope==='1y'||scope==='3y'){const d=new Date(end);d.setUTCFullYear(d.getUTCFullYear()-(scope==='1y'?1:3));start=d.toISOString().slice(0,10);}return {start:daily.start&&start<daily.start?daily.start:start,end};},[daily,scope,custom]);
 const result=useMemo(()=>performanceRange(daily,bounds.start,bounds.end) as unknown as Range,[daily,bounds]);
 const rows=result.points,selectedPoint=selected==null?null:rows[selected],validRange=bounds.start<=bounds.end;
 const months=year==='recent'?result.months.slice(-12):result.months.filter(m=>m.month.startsWith(year));const years=[...new Set(result.months.map(m=>m.month.slice(0,4)))].reverse();
 const problemRows=rows.filter(p=>p.issues.length||Object.values(p.benchmarkProblems).some(v=>v.length));
 const zoom=(start:string,end:string)=>{setScope('custom');setCustom({start,end});setSelected(null);};
 const choose=(value:string)=>{setScope(value);setSelected(null);setDataPage(0);};
 const toggle=(key:Series)=>setVisible(current=>current.includes(key)?current.filter(k=>k!==key):[...current,key]);
 return <InfoPopoverGroup><div className="performance-workspace"><header className="performance-title"><div><h1>績效回顧</h1><p className="desktop-only">投資組合與 QQQ／SPY 的長期成長及回撤</p><span className="mobile-only">歷史績效<InfoPopover label="歷史績效"><p>投資組合與 QQQ／SPY 的長期成長及回撤。各圖共用所選區間，缺資料不補造數值。</p></InfoPopover></span></div><span role="status">{status}<button type="button" className="text-button" disabled={loading} onClick={()=>void resource.retry()}>重試缺漏</button></span></header>
 <div className="performance-controls"><div className="performance-periods" aria-label="績效區間">{[['all','全部'],['ytd','YTD'],['1y','近一年'],['3y','近三年'],['custom','自訂']].map(([value,label])=><button key={value} type="button" aria-pressed={scope===value} onClick={()=>choose(value)}>{label}</button>)}</div>{scope==='custom'&&<div className="performance-dates"><label>起始<input type="date" value={custom.start||daily.start||''} max={daily.end} onChange={e=>{setCustom({...custom,start:e.target.value});setSelected(null);}}/></label><label>結束<input type="date" value={custom.end||daily.end} max={daily.end} onChange={e=>{setCustom({...custom,end:e.target.value});setSelected(null);}}/></label></div>}<div className="performance-series">{keys.map(k=><button key={k} type="button" aria-pressed={visible.includes(k)} onClick={()=>toggle(k)}><i style={{borderColor:colors[k],borderStyle:k==='portfolio'?'solid':k==='QQQ'?'dashed':'dotted'}}/>{names[k]}</button>)}</div></div>
 <div className="performance-period-note">{history&&daily.start?`${result.start} ～ ${result.end}・${currency} 日終估值`:'等待可用歷史區間'}<InfoPopover label="績效計算" mobilePresentation="sheet"><p>每日 Modified Dietz 估算後連乘，排除外部入出金；股息、利息及已登錄費用保留在績效中。依帳本 UTC 日界線計算；只有日期的資金流採日中權重 0.5，並非精確時間加權報酬。</p><p>各帳戶保留原幣現金餘額，依所選計價幣別逐日估值。成交與資金流使用發生日匯率，現金及持倉使用估值日匯率。</p><p>QQQ／SPY 採調整後收盤價估算含息報酬；台幣模式依各日有效匯率換算，所有系列以相同起點重設為 0%。最早日終估值是起點，當日之前的報酬不計。資料截止至共同可用的已完成歷史日，未含即時或當日未完成行情。</p><p>缺資料或期初餘額校正時中斷累積，不跨缺口連線。可縮小日期至完整區間查看。</p><p>歷史行情在載入帳本後背景預載，使用當次記憶體快取；最近一週每六小時重新核對。</p><button type="button" className="ghost" disabled={loading} onClick={()=>void resource.refresh()}>重新下載歷史行情</button></InfoPopover></div>
 {!validRange?<p role="alert">結束日期不能早於起始日期。</p>:!history?<div className="performance-empty">{status}</div>:!rows.length?<div className="performance-empty">尚無可回顧的帳本歷史資料。</div>:<>
 <div className="performance-kpis">{([...keys,'maxDrawdown'] as const).map(k=><div key={k}><span>{k==='maxDrawdown'?'組合最大回撤':names[k]+'累積報酬'}</span><strong className={result.summary[k]==null?'muted':result.summary[k]!>=0?'positive':'negative'}><FitNumber>{result.summary[k]==null?'資料不足':percent(result.summary[k])}</FitNumber></strong></div>)}</div>
 <section className="performance-chart-section"><div className="performance-chart-heading"><h2>累積報酬<InfoPopover label="累積報酬操作"><p>點按或鍵盤選取日期查看數值；桌面可拖選區間，手機可使用上方日期篩選。</p></InfoPopover></h2><span><button type="button" className="text-button" onClick={()=>choose('all')}>還原全部</button></span></div><div className="performance-chart-body"><PerformanceChart key={result.start+result.end} points={rows} visible={visible} selected={selected} onSelect={setSelected} onZoom={zoom}/>{selectedPoint&&<div className="performance-tooltip" role="status"><strong>{selectedPoint.date}</strong><div>{keys.map(k=><span key={k}>{names[k]} {percent(k==='portfolio'?selectedPoint.portfolio:selectedPoint.returns[k])}</span>)}</div><small>淨值 {dollars(selectedPoint.total)}・相對 QQQ {difference(selectedPoint.portfolio,selectedPoint.returns.QQQ)}・相對 SPY {difference(selectedPoint.portfolio,selectedPoint.returns.SPY)}</small>{selectedPoint.issues.length>0&&<small>{selectedPoint.issues.join('；')}</small>}</div>}</div></section>
 <section className="performance-chart-section"><div className="performance-chart-heading"><h2>回撤<InfoPopover label="回撤" mobilePresentation="sheet"><p>累積報酬指數相對所選期間此前最高值的跌幅。最大回撤為本區間最深跌幅，日終估算不含盤中低點。</p></InfoPopover></h2><label><input type="checkbox" checked={ddEtfs} onChange={e=>setDdEtfs(e.target.checked)}/>顯示 ETF 回撤</label></div><PerformanceChart points={rows} drawdown visible={ddEtfs?visible:visible.filter(k=>k==='portfolio')} selected={selected} onSelect={setSelected} onZoom={zoom}/><div className="performance-drawdown-readout">{selectedPoint&&<>{selectedPoint.date} 組合 {percent(selectedPoint.drawdown)}{ddEtfs&&` QQQ ${percent(selectedPoint.drawdowns.QQQ)} SPY ${percent(selectedPoint.drawdowns.SPY)}`}</>}</div></section>
 <section className="performance-chart-section"><div className="performance-chart-heading"><h2>月度報酬<InfoPopover label="月度報酬" mobilePresentation="sheet"><p>每月由有效日報酬連乘；缺資料的月份顯示「—」。選取區間的首尾月可能為部分期間，不會用完整月份冒充。</p></InfoPopover></h2><label>查看月份<select value={years.includes(year)?year:'recent'} onChange={e=>setYear(e.target.value)}><option value="recent">最近 12 個月</option>{years.map(y=><option key={y}>{y}</option>)}</select></label></div><MonthChart months={months} visible={visible}/><details><summary>月度數據</summary><div className="table-wrap"><table><thead><tr><th>月份</th>{keys.map(k=><th key={k}>{names[k]}</th>)}</tr></thead><tbody>{months.map(m=><tr key={m.month}><td>{m.month}{m.partial?'（部分期間）':''}</td>{keys.map(k=><td key={k}>{percent(m[k])}</td>)}</tr>)}</tbody></table></div></details></section>
 <details className="performance-data" onToggle={e=>setDataOpen(e.currentTarget.open)}><summary>估值與資料狀態{problemRows.length?`・${problemRows.length} 日需核對`:''}</summary>{history.errors.map((e:string)=><p key={e}>{e}</p>)}{dataOpen&&<><div className="performance-data-pages"><button type="button" disabled={dataPage===0} onClick={()=>setDataPage(n=>Math.max(0,n-1))}>上一頁</button><span>{Math.min(dataPage*100+1,rows.length)}～{Math.min((dataPage+1)*100,rows.length)}／{rows.length} 日</span><button type="button" disabled={(dataPage+1)*100>=rows.length} onClick={()=>setDataPage(n=>n+1)}>下一頁</button></div><div className="table-wrap" tabIndex={0} role="region" aria-label="每日績效與估值明細"><table><thead><tr><th>日期</th><th>淨值 {currency}</th><th>淨入出金 {currency}</th><th>組合日報酬</th><th>組合累積</th><th>QQQ 累積</th><th>SPY 累積</th><th>資料狀態／實際報價日期</th></tr></thead><tbody>{rows.slice(dataPage*100,(dataPage+1)*100).map(p=><tr key={p.date}><td>{p.date}</td><td>{dollars(p.total)}</td><td>{dollars(p.flow)}</td><td>{percent(p.rate)}</td><td>{percent(p.portfolio)}</td><td>{percent(p.returns.QQQ)}</td><td>{percent(p.returns.SPY)}</td><td>{[...p.issues,...Object.values(p.benchmarkProblems).flat(),...p.warnings].join('；')||'完整'}<small>{Object.entries(p.quoteDates).map(([s,d])=>`${s} ${d}`).join('・')}</small></td></tr>)}</tbody></table></div></>}</details>
 </>}{history?.errors.length&&!rows.length?<div role="alert">{history.errors.join('；')}</div>:null}</div></InfoPopoverGroup>;
}
