/* eslint-disable @typescript-eslint/no-explicit-any */
"use client";
import {useWorkspacePreferences} from './workspace-preferences';
import {useEffect,useRef,useState} from 'react';
import {TradeEntryWorkspace} from './trade-entry-workspace';
import {InfoPopover} from './info-popover';
import {ACTION_LABELS,marketDate} from '@/lib/trade-entry.mjs';
import {ENTRY_MARKETS,newSimpleRow,previewSimpleBatch,resolveSymbolMarket,simpleTimeLabel} from '@/lib/simple-entry.mjs';

export function TradeRegistration({data,quotes,onFullChange,onFullSubmit,onSimpleChange,onSimpleSubmit,onBack,fetcher=fetch,now,ledgerVersion}:any){
 const {preferences,ready,update}=useWorkspacePreferences();const mode=preferences.entryMode;
 const changeMode=(value:string)=>{void update({entryMode:value}).catch(()=>{});};
 return <section className="registration-workspace"><div className="registration-toolbar"><div role="group" aria-label="登錄模式">{[['simple','簡易登錄'],['full','完整登錄']].map(([key,label])=><button type="button" key={key} className="ghost" disabled={!ready} aria-pressed={mode===key} onClick={()=>changeMode(key)}>{label}</button>)}</div><InfoPopover label="交易登錄" mobilePresentation="sheet"><p>只記錄已成交交易，不會送出券商訂單。簡易模式一次登錄同日期、同帳戶的多筆成交；策略與計畫可之後補充。</p><p>補登依成交順序重算 FIFO 與閉環。原註記保留；無法明確對應的資料可在「成交與資金 → 資料檢查」核對。</p><p>切換模式保留各自草稿。雲端是正式帳本；當頁修改會先保存在此裝置，再於背景同步，仍可匯出 JSON 備份。</p></InfoPopover><button className="ghost registration-back" type="button" onClick={onBack}>返回總覽</button></div>{mode==='full'?<TradeEntryWorkspace data={data} draft={data.entryDraft} quotes={quotes} onChange={onFullChange} onSubmit={onFullSubmit} onBack={onBack}/>:<SimpleEntry data={data} batch={data.simpleEntryDraft} onChange={onSimpleChange} onSubmit={onSimpleSubmit} quotes={quotes} fetcher={fetcher} now={now} ledgerVersion={ledgerVersion}/>}</section>;
}
function SimpleEntry({data,batch,onChange,onSubmit,quotes,fetcher,now,ledgerVersion}:any){
 const [preview,setPreview]=useState<any>(null),[error,setError]=useState(''),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false);
 const [discovered,setDiscovered]=useState<Record<string,any>>({});const guard=useRef(false);const focusRow=useRef<string|null>(null);
 useEffect(()=>{if(focusRow.current){document.getElementById(`${focusRow.current}-symbol`)?.focus();focusRow.current=null;}},[batch?.rows.length]);
 const account=data.accounts.find((a:any)=>a.id===batch?.accountId),currency=account?.currency||'USD';
 const allQuotes={...quotes,...discovered};
 const symbols=[...new Set<string>((batch?.rows||[]).map((r:any)=>String(r.symbol).trim().toUpperCase()).filter((s:string)=>/^[A-Z0-9.^=-]{1,20}$/.test(s)))];
 const lookup=symbols.filter(s=>!resolveSymbolMarket(data,s,currency,allQuotes)).flatMap(s=>currency==='TWD'&&!/\.(TW|TWO)$/.test(s)?[`${s}.TW`,`${s}.TWO`]:[s]).join(',');
 useEffect(()=>{
  if(!lookup)return;const controller=new AbortController();
  const timer=setTimeout(()=>{void (async()=>{const symbols=lookup.split(',');for(let i=0;i<symbols.length;i+=50){const response=await fetcher(`/api/quotes?symbols=${encodeURIComponent(symbols.slice(i,i+50).join(','))}`,{signal:controller.signal});if(response.ok){const body=await response.json();if(!controller.signal.aborted)setDiscovered(previous=>({...previous,...Object.fromEntries((body.quotes||[]).map((q:any)=>[q.symbol,q]))}));}}})().catch(()=>{/* Manual market confirmation remains available. */});},400);
  return()=>{clearTimeout(timer);controller.abort();};
 },[lookup,fetcher]);
 if(!batch)return <p>正在準備登錄表單…</p>;
 const effective={...batch,rows:batch.rows.map((r:any)=>({...r,market:r.market||resolveSymbolMarket(data,r.symbol,currency,allQuotes)}))};
 const change=(next:any)=>{setPreview(null);setConfirmed(false);setError('');onChange(next);};
 const rowChange=(id:string,patch:any)=>change({...batch,rows:batch.rows.map((r:any)=>r.id===id?{...r,...patch}:r)});
 const count=batch.rows.filter((r:any)=>String(r.symbol||'').trim()||String(r.quantity||'').trim()||String(r.price||'').trim()||Number(r.fee||0)!==0).length;
 const inspect=()=>{const p=previewSimpleBatch(data,effective,now||new Date().toISOString());setPreview({...p,ledgerVersion});setConfirmed(false);setError('');};
 const submit=async()=>{if(guard.current||!confirmed)return;guard.current=true;setBusy(true);try{await onSubmit(effective,preview.confirmationKey,preview.ledgerVersion);}catch(e){setError(e instanceof Error?e.message:'登錄失敗');setConfirmed(false);}finally{guard.current=false;setBusy(false);}};
 return <form className="simple-entry" noValidate onSubmit={e=>{e.preventDefault();if(preview?.confirmationKey&&confirmed)void submit();else inspect();}}>
 <div className="simple-entry-context"><label>成交日期<input type="date" value={batch.date} max={marketDate(now||new Date().toISOString(),currency==='TWD'?'TWSE':'NASDAQ')} onChange={e=>change({...batch,date:e.target.value})}/></label><label>交易帳戶<select value={batch.accountId} onChange={e=>change({...batch,accountId:e.target.value,rows:batch.rows.map((r:any)=>({...r,market:''}))})}><option value="">選擇帳戶</option>{data.accounts.map((a:any)=><option key={a.id} value={a.id}>{a.name} · {a.currency}</option>)}</select></label><div className="simple-entry-timezone"><span>{currency==='TWD'?'台北':'紐約'}交易日期</span><InfoPopover label="成交日期與時間" mobilePresentation="sheet"><p>當日採提交時刻；過去日期使用台股 13:30／美股 16:00 一般收盤時間，依市場時區轉為 UTC，並處理美股夏令時間。</p><p>這是系統代填，並非精確成交時間。特殊時段、半日市請使用完整登錄。同時刻依下方列序配對 FIFO。</p></InfoPopover></div></div>
 <div className="simple-entry-rows">{effective.rows.map((row:any,index:number)=><fieldset className="simple-entry-row" key={row.id}><legend className="sr-only">第 {index+1} 筆成交</legend><label>標的<input autoComplete="off" id={`${row.id}-symbol`} aria-label={`第 ${index+1} 筆標的`} placeholder="例：NVTS" value={row.symbol} onChange={e=>rowChange(row.id,{symbol:e.target.value.toUpperCase(),market:''})}/></label><label>買賣<select aria-label={`第 ${index+1} 筆買賣`} value={row.side} onChange={e=>rowChange(row.id,{side:e.target.value})}><option value="BUY">買進／回補</option><option value="SELL">賣出／放空</option></select></label>{[['quantity','股數'],['price',`成交價 (${currency})`],['fee',`手續費 (${currency})`]].map(([key,label])=><label key={key}>{label}<input type="number" inputMode="decimal" min="0" step="any" aria-label={`第 ${index+1} 筆${label}`} value={row[key]} onChange={e=>rowChange(row.id,{[key]:e.target.value})}/></label>)}<button type="button" className="ghost simple-row-delete" aria-label={`刪除第 ${index+1} 筆`} onClick={()=>change({...batch,rows:batch.rows.length===1?[newSimpleRow()]:batch.rows.filter((r:any)=>r.id!==row.id)})}><svg width="18" height="18" viewBox="0 0 24 24" aria-hidden="true"><path d="M5 7h14M9 7V4h6v3M7 7l1 13h8l1-13M10 10v7m4-7v7" fill="none" stroke="currentColor" strokeWidth="1.7"/></svg></button>{row.symbol&&<div className={`simple-market ${row.market?'resolved':'unresolved'}`}>{row.market?<details><summary aria-label={`第 ${index+1} 筆市場設定`}>{row.market}</summary><select aria-label={`第 ${index+1} 筆市場`} value={row.market} onChange={e=>rowChange(row.id,{market:e.target.value})}>{ENTRY_MARKETS.map(m=><option key={m}>{m}</option>)}</select></details>:<label>請確認市場<select aria-label={`第 ${index+1} 筆市場`} value="" onChange={e=>rowChange(row.id,{market:e.target.value})}><option value="">選擇交易所</option>{ENTRY_MARKETS.map(m=><option key={m}>{m}</option>)}</select></label>}</div>}{preview?.errors.filter((e:any)=>e.rowId===row.id).map((e:any)=><p className="entry-warning simple-row-error" role="alert" key={e.message}>{e.message}</p>)}</fieldset>)}</div>
 {preview?.errors.filter((e:any)=>!e.rowId).map((e:any)=><p role="alert" key={e.message}>{e.message}</p>)}
 {preview?.confirmationKey&&<section className="simple-confirmation" aria-label="整批成交確認"><h3>確認 {preview.rows.length} 筆成交</h3><ol>{preview.rows.map((r:any)=><li key={r.id}><b>{r.fill.symbol} · {ACTION_LABELS[r.action as keyof typeof ACTION_LABELS]}</b><span>{r.before} → {r.after} 股 · {simpleTimeLabel(r.fill.timeSource)}</span>{r.duplicate&&<strong className="entry-warning">疑似重複成交，請核對</strong>}{r.affected.length>0&&<strong className="entry-warning">補登將調整既有閉環，原註記保留供核對</strong>}</li>)}</ol><label className="entry-confirm"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>確認以上成交、列序及補登影響</label></section>}
 {error&&<p role="alert" className="entry-warning">{error}</p>}<footer className="simple-entry-actions"><button type="button" className="ghost" disabled={batch.rows.length>=100||busy} onClick={()=>{const row=newSimpleRow();focusRow.current=row.id;change({...batch,rows:[...batch.rows,row]});}}>新增一筆</button><button className="primary" type="submit" disabled={busy||!!preview?.confirmationKey&&!confirmed}>{busy?'登錄中…':`登錄 ${preview?.confirmationKey?preview.rows.length:count} 筆成交`}</button><small>{batch.rows.length} / 100 筆</small></footer>
 </form>;
}
export function CycleRebuildHistory({records=[]}:any){return <details className="panel"><summary>補登與閉環重算紀錄・{records.length} 次</summary>{[...records].reverse().map((record:any)=><details key={record.id}><summary>{new Date(record.timestamp).toLocaleString('zh-TW')} · {record.changes.length} 個調整</summary>{record.changes.map((c:any)=><p key={c.from}>{c.symbol} · {c.automatic?'已對應':'待核對'} · {c.from} → {c.to.join('、')||'無單一對應'}</p>)}<details><summary>原始註記備份</summary><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{JSON.stringify(record.original,null,2)}</pre></details></details>)}</details>;}
