/* eslint-disable @typescript-eslint/no-explicit-any */
"use client";

import { useMemo, useState } from "react";
import { activeStrategyVersion, buildStrategyAnalysis, createStrategy, createStrategyAssignment, publishStrategyVersion, ruleApplies } from "@/lib/strategy-engine.mjs";

const GROUP_LABEL: Record<string, string> = { MARKET_CONDITION: "市場條件", ENTRY_TRIGGER: "進場觸發", EXIT_TRIGGER: "出場觸發" };
const APPLIES_LABEL: Record<string, string> = { ALWAYS: "所有交易", WINNING_POSITION: "獲利部位", LOSING_POSITION: "虧損部位" };
const POST_LABEL: Record<string, string> = { UNREVIEWED: "待稽核", FOLLOWED: "遵守", VIOLATED: "違反", NOT_APPLICABLE: "不適用" };
const PRE_LABEL: Record<string, string> = { UNREVIEWED: "待確認", CONFIRMED: "符合", NOT_MET: "未符合" };

function percentage(value: number | null) { return value == null ? "—" : `${(value * 100).toFixed(1)}%`; }
function usd(value: number | null) { return value == null ? "—" : new Intl.NumberFormat("zh-TW", { style: "currency", currency: "USD", currencyDisplay: "code", maximumFractionDigits: 0 }).format(value); }

export function StrategyChecklist({ cycle, strategies, assignment, phase, onAssign, onCheck }: { cycle: any; strategies: any[]; assignment?: any; phase: "pre" | "post"; onAssign: (cycle: any, strategyId: string, source: string) => void; onCheck: (cycleId: string, phase: "pre" | "post", ruleId: string, status: string, note: string) => void }) {
  const active = strategies.filter((strategy) => strategy.status === "ACTIVE" && activeStrategyVersion(strategy));
  const strategy = strategies.find((item) => item.id === assignment?.strategyId);
  const version = strategy?.versions?.find((item: any) => item.id === assignment?.strategyVersionId);
  const rules = (version?.rules || []).filter((rule: any) => phase === "pre" ? rule.group !== "EXIT_TRIGGER" : ruleApplies(rule, cycle));
  const checks = phase === "pre" ? assignment?.preChecks || {} : assignment?.postChecks || {};
  const labels = phase === "pre" ? PRE_LABEL : POST_LABEL;
  return <section className="strategy-checklist">
    <div className="strategy-check-head"><div><h3>{phase === "pre" ? "開倉規則確認" : "平倉後規則稽核"}</h3><small>{phase === "pre" ? "市場與進場規則由交易者手動確認。" : "未完成稽核不納入遵守率，但仍計入策略績效。"}</small></div>{!assignment && <label>主策略<select defaultValue="" onChange={(event) => event.target.value && onAssign(cycle, event.target.value, phase === "pre" ? "OPEN_POSITION" : "HISTORICAL_BATCH")}><option value="">選擇啟用策略…</option>{active.map((item) => <option key={item.id} value={item.id}>{item.name}・v{activeStrategyVersion(item)?.version}</option>)}</select></label>}</div>
    {assignment && strategy && version ? <><div className="strategy-assignment-banner"><b>{strategy.name}・v{version.version}</b><span>{assignment.source === "HISTORICAL_BATCH" ? "歷史補登" : assignment.lateAssignment ? "事後指派" : "事前指派"}</span><small>固定版本，不受後續修改影響</small></div>{rules.length ? <div className="strategy-check-rows">{rules.map((rule: any) => { const check = checks[rule.id] || { status: "UNREVIEWED", note: "" }; return <div key={rule.id} className={`strategy-check-row ${String(check.status).toLowerCase()}`}><div><span>{GROUP_LABEL[rule.group]}</span><b>{rule.name}</b><small>{rule.criterion}</small>{rule.group === "EXIT_TRIGGER" && <em>{APPLIES_LABEL[rule.appliesWhen]}</em>}</div><label>結果<select value={check.status} onChange={(event) => onCheck(cycle.id, phase, rule.id, event.target.value, check.note || "")}>{Object.entries(labels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label>證據／備註<input value={check.note || ""} placeholder="價格、時間或判斷依據" onChange={(event) => onCheck(cycle.id, phase, rule.id, check.status, event.target.value)}/></label></div>; })}</div> : <div className="mini-empty">這個版本沒有此階段的規則。</div>}</> : !active.length ? <div className="mini-empty">尚無啟用中的策略，請先到「策略管理」建立並啟用版本。</div> : null}
  </section>;
}

export function StrategyWorkspace({ strategies, assignments, cycles, fxRate, onStrategiesChange, onAssignmentsChange, onSelectCycle }: { strategies: any[]; assignments: Record<string, any>; cycles: any[]; fxRate: number | null; onStrategiesChange: (next: any[]) => void; onAssignmentsChange: (next: Record<string, any>) => void; onSelectCycle: (cycleId: string) => void }) {
  const [selectedId, setSelectedId] = useState(strategies[0]?.id || "");
  const [name, setName] = useState("");
  const [description, setDescription] = useState("");
  const [createError, setCreateError] = useState("");
  const [reason, setReason] = useState("");
  const [batchStrategyId, setBatchStrategyId] = useState("");
  const [batchSymbol, setBatchSymbol] = useState("");
  const [batchDirection, setBatchDirection] = useState("");
  const [batchFrom, setBatchFrom] = useState("");
  const [batchTo, setBatchTo] = useState("");
  const [selectedCycles, setSelectedCycles] = useState<Set<string>>(new Set());
  const selected = strategies.find((strategy) => strategy.id === selectedId) || strategies[0] || null;
  const analysis = useMemo(() => buildStrategyAnalysis(cycles, strategies, assignments, { strategyId: selected?.id || "", usdTwdRate: fxRate }), [assignments, cycles, fxRate, selected?.id, strategies]);
  const activeStrategies = strategies.filter((strategy) => strategy.status === "ACTIVE" && activeStrategyVersion(strategy));
  const batchCycles = useMemo(() => cycles.filter((cycle) => !assignments[cycle.id] && (!batchSymbol || cycle.symbol.includes(batchSymbol.toUpperCase())) && (!batchDirection || cycle.direction === batchDirection) && (!batchFrom || cycle.closeAt.slice(0, 10) >= batchFrom) && (!batchTo || cycle.closeAt.slice(0, 10) <= batchTo)).sort((a, b) => b.closeAt.localeCompare(a.closeAt)), [assignments, batchDirection, batchFrom, batchSymbol, batchTo, cycles]);

  const updateSelected = (patch: any) => selected && onStrategiesChange(strategies.map((strategy) => strategy.id === selected.id ? { ...strategy, ...patch, updatedAt: new Date().toISOString() } : strategy));
  const create = (event?: React.FormEvent) => {
    event?.preventDefault();
    if (!name.trim()) { setCreateError("請先填寫策略名稱；策略說明可留空。"); return; }
    const strategy = createStrategy({ name, description, rules: [] });
    onStrategiesChange([...strategies, strategy]);
    setSelectedId(strategy.id); setName(""); setDescription(""); setCreateError("");
  };
  // The ID is created only when the user clicks “新增規則”, not while rendering.
  // eslint-disable-next-line react-hooks/purity
  const addRule = (group: string) => updateSelected({ draftRules: [...(selected?.draftRules || []), { id: `rule-${Date.now()}`, group, name: "新規則", criterion: "", checkpoint: group === "MARKET_CONDITION" ? "BEFORE_ENTRY" : group === "ENTRY_TRIGGER" ? "AT_ENTRY" : "AT_EXIT", appliesWhen: "ALWAYS", note: "", order: (selected?.draftRules || []).length }] });
  const patchRule = (ruleId: string, patch: any) => updateSelected({ draftRules: (selected?.draftRules || []).map((rule: any) => rule.id === ruleId ? { ...rule, ...patch } : rule) });
  const removeRule = (ruleId: string) => updateSelected({ draftRules: (selected?.draftRules || []).filter((rule: any) => rule.id !== ruleId) });
  const publish = () => { if (!selected || !(selected.draftRules || []).length || selected.versions?.length && !reason.trim()) return; const result = publishStrategyVersion(selected, selected.draftRules || [], reason); onStrategiesChange(strategies.map((item) => item.id === selected.id ? result.strategy : item)); setReason(""); };
  const batchAssign = () => { const strategy = strategies.find((item) => item.id === batchStrategyId); if (!strategy) return; const next = { ...assignments }; for (const cycle of batchCycles.filter((item) => selectedCycles.has(item.id))) next[cycle.id] = createStrategyAssignment(cycle, strategy, "HISTORICAL_BATCH"); onAssignmentsChange(next); setSelectedCycles(new Set()); };

  return <div className="strategy-workspace">
    <section className="strategy-intro"><div><h2>策略管理與逐筆稽核</h2><p>把市場條件、進場觸發與出場觸發固定成不可變版本，讓每筆交易都能回到當時真正使用的規則。</p></div><div><b>{strategies.length}</b><span>帳號策略</span><small>{analysis.reviewedTradeCount < 20 ? `已稽核 ${analysis.reviewedTradeCount}/20・待觀察` : `已稽核 ${analysis.reviewedTradeCount} 筆`}</small></div></section>
    <div className="strategy-layout"><aside className="strategy-list"><form className="strategy-create" onSubmit={create} noValidate><label>策略名稱 <em>必填</em><input aria-invalid={Boolean(createError)} value={name} placeholder="例如：波段突破" onChange={(event) => { setName(event.target.value); if (event.target.value.trim()) setCreateError(""); }}/></label><label>策略說明 <em>選填</em><textarea value={description} placeholder="說明這套策略適用的市場與交易方式" onChange={(event) => setDescription(event.target.value)}/></label>{createError && <p className="strategy-create-error" role="alert">{createError}</p>}<button className="primary" type="submit">建立草稿</button></form>{strategies.map((strategy) => <button type="button" key={strategy.id} className={selected?.id === strategy.id ? "selected" : ""} onClick={() => setSelectedId(strategy.id)}><span><b>{strategy.name}</b><small>{strategy.status === "ACTIVE" ? `啟用中・v${activeStrategyVersion(strategy)?.version}` : strategy.status === "ARCHIVED" ? "已封存" : "草稿"}</small></span><i>{strategy.versions?.length || 0}</i></button>)}</aside>
      <div className="strategy-editor">{selected ? <><div className="panel-head"><div><h2>{selected.name}</h2><p>{selected.description || "尚未填寫策略說明"}</p></div><button type="button" className="ghost" onClick={() => updateSelected({ status: selected.status === "ARCHIVED" ? "DRAFT" : "ARCHIVED" })}>{selected.status === "ARCHIVED" ? "恢復草稿" : "封存策略"}</button></div>{Object.entries(GROUP_LABEL).map(([group, label]) => <section className="strategy-rule-group" key={group}><div><b>{label}</b><small>{group === "MARKET_CONDITION" ? "進場前的大盤、產業與環境前提" : group === "ENTRY_TRIGGER" ? "真正觸發成交的可衡量訊號" : "獲利、虧損或所有部位的出場規則"}</small><button className="text-button" type="button" onClick={() => addRule(group)}>＋ 新增規則</button></div>{(selected.draftRules || []).filter((rule: any) => rule.group === group).map((rule: any) => <article key={rule.id} className="strategy-rule-card"><label>規則名稱<input value={rule.name} onChange={(event) => patchRule(rule.id, { name: event.target.value })}/></label><label className="wide">可衡量條件<input value={rule.criterion} placeholder="例：收盤價站上20日均線且成交量大於20日均量1.5倍" onChange={(event) => patchRule(rule.id, { criterion: event.target.value })}/></label><label>檢查時點<input value={({ BEFORE_ENTRY: "進場前", AT_ENTRY: "進場時", AT_EXIT: "出場時" } as Record<string,string>)[rule.checkpoint] || rule.checkpoint} onChange={(event) => patchRule(rule.id, { checkpoint: ({ "進場前": "BEFORE_ENTRY", "進場時": "AT_ENTRY", "出場時": "AT_EXIT" } as Record<string,string>)[event.target.value] || event.target.value })}/></label>{group === "EXIT_TRIGGER" && <label>適用情境<select value={rule.appliesWhen} onChange={(event) => patchRule(rule.id, { appliesWhen: event.target.value })}>{Object.entries(APPLIES_LABEL).map(([value, text]) => <option key={value} value={value}>{text}</option>)}</select></label>}<label className="wide">補充說明<input value={rule.note || ""} onChange={(event) => patchRule(rule.id, { note: event.target.value })}/></label><button type="button" className="danger" onClick={() => removeRule(rule.id)}>刪除</button></article>)}</section>)}<div className="strategy-publish"><label>修改理由<input value={reason} required={Boolean(selected.versions?.length)} placeholder={selected.versions?.length ? "已啟用策略發布新版時必填" : "首次啟用"} onChange={(event) => setReason(event.target.value)}/></label><button type="button" className="primary" disabled={!selected.draftRules?.length || Boolean(selected.versions?.length && !reason.trim()) || selected.status === "ARCHIVED"} onClick={publish}>{selected.versions?.length ? "建立新版本並啟用" : "啟用第一版"}</button></div><div className="strategy-version-history"><b>歷史版本</b>{[...(selected.versions || [])].reverse().map((version: any) => <div key={version.id}><span>v{version.version}・{version.rules.length} 條規則</span><small>{version.changeReason}・{new Date(version.createdAt).toLocaleString("zh-TW", { hour12: false })}</small></div>)}</div></> : <div className="mini-empty">建立第一個策略草稿後，即可編輯三組規則。</div>}</div></div>
    <section className="strategy-analysis-preview"><div className="panel-head"><div><h2>{selected?.name || "全部策略"}稽核摘要</h2></div><span className={`status ${analysis.sampleState === "ESTABLISHED" ? "ok" : "warn"}`}>{analysis.sampleState === "ESTABLISHED" ? "樣本可評估" : "待觀察"}</span></div><div className="strategy-metrics"><div><span>交易數</span><b>{analysis.total.count}</b></div><div><span>稽核覆蓋率</span><b>{percentage(analysis.reviewCoverage)}</b></div><div><span>規則遵守率</span><b>{percentage(analysis.adherenceRate)}</b></div><div><span>完全遵守交易率</span><b>{percentage(analysis.fullComplianceRate)}</b></div><div><span>勝率</span><b>{percentage(analysis.total.winRate)}</b></div><div><span>平均盈虧比</span><b>{analysis.total.rewardRisk?.toFixed(2) || "—"}</b></div><div><span>期望值</span><b>{analysis.total.expectancyR == null ? "—" : `${analysis.total.expectancyR.toFixed(2)}R`}</b></div><div><span>已實現損益</span><b>{usd(analysis.total.totalPnlUsd)}</b></div></div></section>
    <section className="strategy-batch"><div className="panel-head"><div><h2>歷史閉環批次補登</h2><p>批次指派一律標示「歷史補登」，規則初始均為待稽核。</p></div><button className="primary" type="button" disabled={!batchStrategyId || !selectedCycles.size} onClick={batchAssign}>指派 {selectedCycles.size} 筆</button></div><div className="batch-filters"><label>策略<select value={batchStrategyId} onChange={(event) => setBatchStrategyId(event.target.value)}><option value="">選擇啟用策略</option>{activeStrategies.map((strategy) => <option key={strategy.id} value={strategy.id}>{strategy.name}・v{activeStrategyVersion(strategy)?.version}</option>)}</select></label><label>起日<input type="date" value={batchFrom} onChange={(event) => setBatchFrom(event.target.value)}/></label><label>迄日<input type="date" value={batchTo} onChange={(event) => setBatchTo(event.target.value)}/></label><label>標的<input value={batchSymbol} placeholder="全部" onChange={(event) => setBatchSymbol(event.target.value)}/></label><label>方向<select value={batchDirection} onChange={(event) => setBatchDirection(event.target.value)}><option value="">多空全部</option><option value="LONG">多單</option><option value="SHORT">空單</option></select></label></div><div className="table-wrap" tabIndex={0} role="region" aria-label="策略資料表，可捲動"><table><thead><tr><th><input aria-label="選取全部可見閉環" type="checkbox" checked={Boolean(batchCycles.length && batchCycles.every((cycle) => selectedCycles.has(cycle.id)))} onChange={(event) => setSelectedCycles(event.target.checked ? new Set(batchCycles.map((cycle) => cycle.id)) : new Set())}/></th><th>標的</th><th>方向</th><th>期間</th><th>損益</th><th>證據</th></tr></thead><tbody>{batchCycles.slice(0, 100).map((cycle) => <tr key={cycle.id}><td><input aria-label={`選取 ${cycle.symbol} ${cycle.closeAt.slice(0, 10)} 閉環`} type="checkbox" checked={selectedCycles.has(cycle.id)} onChange={(event) => setSelectedCycles((current) => { const next = new Set(current); if (event.target.checked) next.add(cycle.id); else next.delete(cycle.id); return next; })}/></td><td><b>{cycle.symbol}</b></td><td>{cycle.direction === "SHORT" ? "空" : "多"}</td><td>{cycle.openAt.slice(0, 10)} → {cycle.closeAt.slice(0, 10)}</td><td>{cycle.pnl.toFixed(2)} {cycle.currency}</td><td><button className="text-button" type="button" onClick={() => onSelectCycle(cycle.id)}>查看閉環</button></td></tr>)}</tbody></table></div>{!batchCycles.length && <div className="mini-empty">沒有符合條件且尚未指派策略的閉環。</div>}</section>
  </div>;
}
