/* eslint-disable @typescript-eslint/no-explicit-any */
"use client";
import { useEffect, useMemo, useRef, useState } from 'react';
import { activeStrategyVersion, buildStrategyAnalysis, buildStrategyComparison, createStrategy, publishStrategyVersion } from '@/lib/strategy-engine.mjs';
import { GROUP_LABELS, strategyStagesForCycle, strategyV2, validateStrategyDefinition } from '@/lib/strategy-conditions.mjs';
import { StrategyConditions } from './strategy-conditions';
import { InfoPopover, InfoPopoverGroup } from './info-popover';
const APPLIES_LABEL: Record<string, string> = { ALWAYS: '所有交易', WINNING_POSITION: '獲利部位', LOSING_POSITION: '虧損部位' };
export function StrategyChecklist(props: any) {
  const { cycle, strategies, assignment, phase, onStageReview, entryContexts = {} } = props;
  const strategy = strategies.find((item: any) => item.id === assignment?.strategyId);
  const version = strategy?.versions?.find((item: any) => item.id === assignment?.strategyVersionId);
  if (!assignment || !version) return <section className="strategy-checklist"><h3>主策略</h3>{assignment ? <p className="negative">原策略版本遺失，保留既有關聯，請核對帳本。</p> : <label>選擇策略<select aria-label="複盤主策略" defaultValue="" onChange={event => event.target.value && props.onAssign(cycle,event.target.value,'HISTORICAL_BATCH')}><option value="">未指定策略</option>{strategies.filter((item:any)=>item.status==='ACTIVE'&&activeStrategyVersion(item)).map((item:any)=><option key={item.id} value={item.id}>{item.name} · v{activeStrategyVersion(item).version}</option>)}</select></label>}</section>;
  if (phase === 'post' && !strategyV2(version)) return <section className="strategy-checklist"><h3>策略複盤 · {strategy.name} v{version.version}</h3><p className="muted">舊版逐條判定口徑，成交時證據保留。</p><StrategyConditions version={version} phase="ALL" context={cycle} mode="audit" value={{checks:assignment.postChecks||{}}} onChange={value=>{for(const [id,status] of Object.entries(value.checks||{})){const previous=assignment.postChecks?.[id];if(typeof status==='string'&&status!==previous?.status)props.onCheck(cycle.id,'post',id,status,previous?.note||'');}}}/></section>;
  if (phase === 'pre') return <section className="strategy-checklist"><h3>後續策略確認</h3><p>{strategy.name} · v{version.version}</p><StrategyConditions version={version} value={assignment.stageReviews?.[`followup:${cycle.id}`] || {}} onChange={value => onStageReview?.(cycle.id, `followup:${cycle.id}`, value)}/><small>確認時間：{assignment.stageReviews?.[`followup:${cycle.id}`]?.checkedAt || '尚未確認'}；不修改原始開倉證據。</small></section>;
  const stages = strategyStagesForCycle(cycle, entryContexts);
  return <section className="strategy-checklist strategy-stage-audit"><h3>策略複盤 · {strategy.name} v{version.version}</h3><p className="muted">逐次核對成交，原始勾選保留為唯讀證據。</p>{stages.map((stage: any) => <details key={stage.id} open={stages.length <= 2}><summary>{stage.phase === 'ENTRY' ? '進場／加碼' : '減碼／出場'} · {stage.fillTimestamp ? new Date(stage.fillTimestamp).toLocaleString('zh-TW') : '時間未記錄'} · {assignment.stageReviews?.[stage.id]?.checkedAt ? '已有複盤紀錄' : '待複盤'}</summary>{stage.missing ? <p className="muted">成交時策略證據未記錄；下方為事後核對。</p> : <details><summary>成交時確認（唯讀）</summary><StrategyConditions version={stage.versionSnapshot || version} value={stage.selection} phase={stage.phase} context={stage.conditionContext || cycle} mode="readonly"/>{stage.exception && <p className="negative">當時已確認例外登錄 · {stage.exceptionConfirmedAt}</p>}</details>}<StrategyConditions version={stage.versionSnapshot || version} value={assignment.stageReviews?.[stage.id] || {}} phase={stage.phase} context={stage.conditionContext || cycle} mode="audit" onChange={value => onStageReview?.(cycle.id, stage.id, value)}/><small>複盤時間：{assignment.stageReviews?.[stage.id]?.checkedAt || '尚未核對'}</small></details>)}</section>;
}

const money = (value: number | null) => value == null ? '資料不足' : `USD ${Number(value).toLocaleString('en-US', { minimumFractionDigits: 1, maximumFractionDigits: 1 })}`;
const rate = (value: number | null) => value == null ? '資料不足' : `${(value * 100).toFixed(1)}%`;
const fixed = (value: number | null) => value == null ? '資料不足' : value.toFixed(2);
function editable(strategy: any) {
  const version = activeStrategyVersion(strategy);
  return { ...strategy, draftRules: (strategy.draftRules || version?.rules || []).map((rule: any) => ({ ...rule })), draftMarketMode: strategy.draftMarketMode || version?.marketMode || ((strategy.draftRules || version?.rules || []).some((rule: any) => rule.group === 'MARKET_CONDITION') ? 'CUSTOM' : 'UNRESTRICTED') };
}
export function StrategyWorkspace({ strategies, assignments, cycles, fxRate, entryContexts = {}, onStrategiesChange, onDirtyChange, onSelectCycle }: { strategies: any[]; assignments: Record<string, any>; cycles: any[]; fxRate: number | null; entryContexts?: Record<string, any>; onStrategiesChange: (next: any[]) => Promise<void> | void; onDirtyChange?: (dirty: boolean) => void; onSelectCycle?: (id: string) => void }) {
  const [editor, setEditor] = useState<any>(() => strategies[0] ? editable(strategies[0]) : null);
  const [baseline, setBaseline] = useState(() => JSON.stringify(editor));
  const [reason, setReason] = useState('');
  const [errors, setErrors] = useState<Record<string, string>>({});
  const [saveError, setSaveError] = useState(''), [notice, setNotice] = useState(''), [saving, setSaving] = useState(false);
  const pending = useRef<any>(null), busy = useRef(false);
  const [analysisId, setAnalysisId] = useState<string | null>(strategies[0]?.id || null), [versionId, setVersionId] = useState('');
  const [sort, setSort] = useState({ key: 'totalPnlUsd', descending: true });
  const published = activeStrategyVersion(editor);
  const unpublished = !published || JSON.stringify((published.rules || []).map((rule:any)=>({ ...rule, order: undefined }))) !== JSON.stringify((editor?.draftRules || []).map((rule:any)=>({ ...rule, order: undefined }))) || published.marketMode !== editor?.draftMarketMode || published.name !== editor?.name || published.description !== editor?.description;
  const dirty = JSON.stringify(editor) !== baseline || !!reason.trim();
  useEffect(() => { onDirtyChange?.(dirty || !!saveError || saving); return () => onDirtyChange?.(false); }, [dirty, saveError, saving, onDirtyChange]);
  useEffect(() => { if (!dirty && !saveError && !saving) return; const warn = (event: BeforeUnloadEvent) => { event.preventDefault(); event.returnValue = ''; }; window.addEventListener('beforeunload', warn); return () => window.removeEventListener('beforeunload', warn); }, [dirty, saveError, saving]);
  const change = (patch: any) => { setEditor((current: any) => ({ ...current, ...patch })); setErrors({}); setNotice(''); };
  const leave = () => !saving && (!dirty && !saveError || window.confirm('尚有未儲存的策略修改，確定放棄？'));
  const choose = (id: string) => { if (!leave()) return; const next = id ? editable(strategies.find(item => item.id === id)) : null; setEditor(next); setBaseline(JSON.stringify(next)); setReason(''); setErrors({}); setSaveError(''); pending.current = null; };
  const create = () => { if (!leave()) return; const next = { ...createStrategy({ name: '', rules: [] }), id: `strategy-${crypto.randomUUID()}`, draftMarketMode: 'UNRESTRICTED' }; setEditor(next); setBaseline('null'); setErrors({}); setReason(''); setSaveError(''); pending.current = null; };
  const cancel = () => { const stored = strategies.find(item => item.id === editor?.id); const next = stored ? editable(stored) : null; setEditor(next); setBaseline(JSON.stringify(next)); setReason(''); setErrors({}); setNotice('已取消修改'); };
  const patchRule = (id: string, patch: any) => change({ draftRules: editor.draftRules.map((rule: any) => rule.id === id ? { ...rule, ...patch } : rule) });
  const addRule = (group: string) => change({ draftRules: [...editor.draftRules, { id: `rule-${crypto.randomUUID()}`, group, name: '', criterion: '', note: '', appliesWhen: 'ALWAYS', checkpoint: group === 'MARKET_CONDITION' ? 'BEFORE_ENTRY' : group === 'ENTRY_TRIGGER' ? 'AT_ENTRY' : 'AT_EXIT', order: editor.draftRules.length }] });
  async function save(action: 'draft' | 'publish' | 'archive' | 'restore') {
    if (!editor || busy.current) return;
    if (!pending.current) {
      const validation: Record<string,string> = action === 'publish' ? validateStrategyDefinition(editor.name, editor.draftRules, editor.draftMarketMode) : editor.name.trim() ? {} : { name: '請填寫策略名稱' };
      if (action === 'publish' && editor.versions?.length && !reason.trim()) validation.reason = '請填寫本次修改理由';
      if (Object.keys(validation).length) { setErrors(validation); return; }
      let candidate = { ...editor, name: editor.name.trim(), updatedAt: new Date().toISOString() };
      if (action === 'publish') candidate = publishStrategyVersion(candidate, candidate.draftRules, reason, candidate.updatedAt, { formatVersion: 2, marketMode: candidate.draftMarketMode }).strategy;
      if (action === 'archive') candidate.status = 'ARCHIVED';
      if (action === 'restore') candidate.status = candidate.versions?.length ? 'ACTIVE' : 'DRAFT';
      pending.current = candidate;
    }
    busy.current = true; setSaving(true); setSaveError('');
    try {
      const candidate = pending.current;
      const next = strategies.some(item => item.id === candidate.id) ? strategies.map(item => item.id === candidate.id ? candidate : item) : [...strategies, candidate];
      await onStrategiesChange(next);
      const saved = editable(candidate); setEditor(saved); setBaseline(JSON.stringify(saved)); setReason(''); pending.current = null; setNotice('策略已儲存'); setAnalysisId(candidate.id);
    } catch (error) { setSaveError(error instanceof Error ? error.message : '儲存失敗，請重試'); }
    finally { busy.current = false; setSaving(false); }
  }
  const comparison = useMemo(() => buildStrategyComparison(cycles, strategies, assignments, { usdTwdRate: fxRate, entryContexts }), [cycles, strategies, assignments, fxRate, entryContexts]);
  const sorted = [...comparison].sort((a: any, b: any) => { if (!a.id) return 1; if (!b.id) return -1; const x = !a.count && !['name','count'].includes(sort.key) ? null : a[sort.key], y = !b.count && !['name','count'].includes(sort.key) ? null : b[sort.key]; if (x == null) return y == null ? a.name.localeCompare(b.name) : 1; if (y == null) return -1; const d = typeof x === 'string' ? x.localeCompare(y) : x - y; return (sort.descending ? -d : d) || a.name.localeCompare(b.name); });
  const analysis = useMemo(() => buildStrategyAnalysis(cycles, strategies, assignments, { strategyId: analysisId || '', versionId, usdTwdRate: fxRate, entryContexts }), [cycles, strategies, assignments, analysisId, versionId, fxRate, entryContexts]);
  const selectedStrategy = strategies.find(item => item.id === analysisId);
  const columns = [['name','策略'],['count','已平倉'],['winRate','勝率'],['totalProfitUsd','總獲利'],['totalLossUsd','總虧損'],['totalPnlUsd','淨損益'],['rewardRisk','平均盈虧比'],['expectancyR','期望值']];
  return <InfoPopoverGroup><div className="strategy-v2">
    <div className="strategy-toolbar"><h2>策略管理</h2><label><span className="sr-only">選擇策略</span><select aria-label="選擇策略" value={strategies.some(item => item.id === editor?.id) ? editor.id : ''} disabled={saving || !!saveError} onChange={event => choose(event.target.value)}><option value="">{editor ? '新策略草稿' : '選擇策略'}</option>{strategies.map(item => <option key={item.id} value={item.id}>{item.name} · {item.status === 'ARCHIVED' ? '已封存' : item.status === 'DRAFT' ? '草稿' : `v${activeStrategyVersion(item)?.version}`}</option>)}</select></label><button type="button" onClick={create} disabled={saving || !!saveError}>新增策略</button>{editor && <span className="muted">{editor.status === 'ACTIVE' ? `啟用中 · v${activeStrategyVersion(editor)?.version}` : editor.status === 'ARCHIVED' ? '已封存' : '草稿'}{dirty ? ' · 未儲存' : ''}</span>}</div>
    {editor ? <section className="strategy-editor-v2"><fieldset disabled={saving || !!saveError || editor.status === 'ARCHIVED'}><div className="strategy-basics"><label>策略名稱<input value={editor.name} aria-invalid={!!errors.name} onChange={event => change({ name: event.target.value })} placeholder="例如：波段突破"/>{errors.name && <small role="alert" className="negative">{errors.name}</small>}</label><label>策略說明（選填）<input value={editor.description || ''} onChange={event => change({ description: event.target.value })}/></label></div>
    <div className="strategy-definition-grid">{Object.entries(GROUP_LABELS).map(([group, label]) => <section key={group}><div className="strategy-group-title"><h3>{label}</h3><InfoPopover label={label}><p>{group === 'MARKET_CONDITION' ? '不限市場不需要勾選；自訂市場條件須全部符合。' : '成交時可多選，至少符合一項。內容由你自行定義。'}</p></InfoPopover></div>{group === 'MARKET_CONDITION' ? <label><span className="sr-only">市場模式</span><select aria-label="市場模式" value={editor.draftMarketMode} onChange={event => change({ draftMarketMode: event.target.value })}><option value="UNRESTRICTED">不限市場（標準）</option><option value="CUSTOM">自訂市場條件・全部符合</option></select></label> : <p className="muted strategy-match-note">多選 · 至少符合一項</p>}
      {group === 'MARKET_CONDITION' && editor.draftMarketMode === 'UNRESTRICTED' ? <p className="muted">適用全部市場環境。{editor.draftRules.some((rule: any) => rule.group === group) ? '原自訂條件保留，切回自訂即可編輯。' : ''}</p> : <>{editor.draftRules.filter((rule: any) => rule.group === group).map((rule: any, index: number) => <div className="strategy-definition-row" key={rule.id}><label><span className="sr-only">{label} {index + 1}</span><input aria-label={`${label} ${index + 1}`} aria-invalid={!!errors[rule.id]} value={rule.name} placeholder="輸入條件內容" onChange={event => patchRule(rule.id, { name: event.target.value })}/></label><button type="button" className="strategy-remove" aria-label={`刪除${label} ${index + 1}`} onClick={() => change({ draftRules: editor.draftRules.filter((item: any) => item.id !== rule.id) })}><svg width="16" height="16" viewBox="0 0 16 16" aria-hidden="true"><path d="m4 4 8 8m0-8-8 8" stroke="currentColor" strokeWidth="1.5"/></svg></button>{errors[rule.id] && <small role="alert" className="negative">{errors[rule.id]}</small>}<details><summary>補充說明{rule.appliesWhen && rule.appliesWhen !== 'ALWAYS' ? ' · 限定情境' : ''}</summary><label>判斷依據<input value={rule.criterion || ''} onChange={event => patchRule(rule.id, { criterion: event.target.value })}/></label><label>備註<input value={rule.note || ''} onChange={event => patchRule(rule.id, { note: event.target.value })}/></label>{group === 'EXIT_TRIGGER' && <label>適用情境<select value={rule.appliesWhen || 'ALWAYS'} onChange={event => patchRule(rule.id, { appliesWhen: event.target.value })}>{Object.entries(APPLIES_LABEL).map(([key, value]) => <option key={key} value={key}>{value}</option>)}</select></label>}</details></div>)}<button type="button" className="text-button" onClick={() => addRule(group)}>新增{label}</button>{errors[group] && <p role="alert" className="negative">{errors[group]}</p>}</>}
    </section>)}</div>{editor.versions?.length > 0 && <label className="strategy-change-reason">發布新版的修改理由<input value={reason} placeholder="僅儲存草稿時可留空" onChange={event => { setReason(event.target.value); setErrors({}); }}/>{errors.reason && <small role="alert" className="negative">{errors.reason}</small>}</label>}</fieldset>
    <div className="strategy-save-actions">{saveError ? <button type="button" className="primary" disabled={saving} onClick={() => save('draft')}>{saving ? '儲存中…' : '重試儲存'}</button> : <><button type="button" disabled={saving || !dirty} onClick={cancel}>取消修改</button><button type="button" disabled={saving || !dirty || editor.status === 'ARCHIVED'} onClick={() => save('draft')}>儲存草稿</button><button type="button" className="primary" disabled={saving || editor.status === 'ARCHIVED' || !unpublished} onClick={() => save('publish')}>{saving ? '儲存中…' : editor.versions?.length ? '發布新版' : '建立並啟用'}</button></>}<span role="status">{notice}</span></div>{saveError && <p role="alert" className="negative">{saveError}。草稿保留，重試不會重複發布版本。</p>}
    <details className="strategy-history"><summary>版本與其他操作 · {editor.versions?.length || 0} 個版本</summary><p className="muted">新版本適用新建部位；既有持倉與成交證據維持原版本。</p>{[...(editor.versions || [])].reverse().map((version: any) => <details key={version.id}><summary>v{version.version} · {version.changeReason} · {new Date(version.createdAt).toLocaleString('zh-TW')}</summary><p>{version.formatVersion === 2 ? '市場全部符合／進出場任一符合' : '舊版逐條判定口徑'}</p>{version.rules.map((rule: any) => <p key={rule.id}>{GROUP_LABELS[rule.group as keyof typeof GROUP_LABELS]}：{rule.name}{rule.criterion ? ` · ${rule.criterion}` : ''}{rule.note ? ` · ${rule.note}` : ''}</p>)}</details>)}<button type="button" disabled={saving || !!saveError || dirty} onClick={() => save(editor.status === 'ARCHIVED' ? 'restore' : 'archive')}>{editor.status === 'ARCHIVED' ? '恢復策略' : '封存策略'}</button></details>
    </section> : <div className="mini-empty">新增策略，設定市場、進場與出場條件後即可啟用。</div>}
    <section className="strategy-performance"><div className="strategy-group-title"><h2>策略損益</h2><InfoPopover label="策略損益"><p>全期間已平倉閉環，每個閉環僅計算一次；未複盤仍計入損益。封存策略的歷史交易保留。</p><p>勝率＝獲利筆數 ÷ 獲利與虧損筆數。平均盈虧比＝平均獲利率 ÷ 平均虧損率絕對值。期望值＝勝率 × 平均盈虧比 −（1 − 勝率）。</p><p>台幣損益沿用帳本目前 USD/TWD 換算（{fxRate ?? '資料不足'}）；不是歷史匯率績效。金額已含帳本登錄費用。</p></InfoPopover><span className="muted">已平倉 · 全期間</span></div><div className="table-wrap"><table><thead><tr>{columns.map(([key,label]) => <th key={key} aria-sort={sort.key === key ? sort.descending ? 'descending' : 'ascending' : 'none'}><button type="button" onClick={() => setSort({ key, descending: sort.key === key ? !sort.descending : key !== 'name' })}>{label}<span aria-hidden="true">{sort.key === key ? sort.descending ? ' ↓' : ' ↑' : ' ↕'}</span></button></th>)}</tr></thead><tbody>{sorted.map((row: any) => <tr key={row.id || 'unassigned'} className={analysisId === row.id ? 'selected' : ''}><td><button type="button" onClick={() => { setAnalysisId(row.id); setVersionId(''); }}>{row.name}</button>{row.status === 'ARCHIVED' && <small>已封存</small>}</td><td>{row.count}</td><td>{row.count ? rate(row.winRate) : '—'}</td>{['totalProfitUsd','totalLossUsd','totalPnlUsd'].map(key => <td className={row[key] < 0 ? 'negative' : row[key] > 0 ? 'positive' : ''} key={key}>{row.count ? money(row[key]) : '—'}</td>)}<td>{row.count ? fixed(row.rewardRisk) : '—'}</td><td>{row.count && row.expectancyR != null ? `${fixed(row.expectancyR)}R` : row.count ? '資料不足' : '—'}</td></tr>)}{!sorted.length && <tr><td colSpan={8}>尚無已平倉交易</td></tr>}</tbody></table></div>
    {analysisId !== null && <div className="strategy-analysis-detail"><div className="strategy-group-title"><h3>{selectedStrategy?.name || '未指定策略'}</h3><InfoPopover label="策略複盤統計"><p>舊版保留逐條判定；新版以每次操作的條件組判定，進出場任一符合即可。可篩選版本比較相同口徑。</p><p>複盤覆蓋率需所有必要階段完成核對。交易分成全部符合、已有未符合及尚待判定三組；成交時的勾選不自動算作完成複盤。</p></InfoPopover>{selectedStrategy && <select aria-label="績效策略版本" value={versionId} onChange={event => setVersionId(event.target.value)}><option value="">所有版本</option>{selectedStrategy.versions.map((version: any) => <option key={version.id} value={version.id}>v{version.version}</option>)}</select>}</div>{selectedStrategy ? <><div className="strategy-performance-summary"><span>平均獲利率 <b>{rate(analysis.total.averageWin)}</b></span><span>平均虧損率 <b>{rate(analysis.total.averageLoss)}</b></span><span>複盤覆蓋率 <b>{rate(analysis.reviewCoverage)}</b></span><span>遵守率 <b>{rate(analysis.adherenceRate)}</b></span></div><p>全部符合 {analysis.compliant.count} 筆 · {money(analysis.compliant.totalPnlUsd)} ／ 存在未符合 {analysis.violated.count} 筆 · {money(analysis.violated.totalPnlUsd)} ／ 待判定 {analysis.rows.filter((row: any) => !row.reviewed && !row.violated).length} 筆</p>{analysis.total.count < 20 && <small className="muted">樣本少於 20 筆，績效僅供回顧。</small>}</> : <p className="muted">未指定或版本遺失的交易，不納入策略遵守率。</p>}<details><summary>查看閉環證據</summary><div className="strategy-cycle-links">{(selectedStrategy ? analysis.rows.map((row: any) => row.cycle) : cycles.filter(cycle => !assignments[cycle.id] || !strategies.some(strategy => strategy.id === assignments[cycle.id].strategyId && strategy.versions?.some((version: any) => version.id === assignments[cycle.id].strategyVersionId)))).sort((a: any,b: any) => String(b.closeAt).localeCompare(String(a.closeAt))).map((cycle: any) => <button type="button" key={cycle.id} onClick={() => onSelectCycle?.(cycle.id)}>{cycle.symbol} · {cycle.closeAt?.slice(0,10)} · {cycle.currency} {Number(cycle.pnl).toFixed(1)}</button>)}</div>{selectedStrategy && !analysis.total.count && <p>尚無已平倉交易</p>}</details></div>}
    </section>
  </div></InfoPopoverGroup>;
}
