/* eslint-disable @next/next/no-img-element -- Fixed-size identity-provider avatar; no image proxy or additional remote access. */
"use client";
import {useEffect, useRef, useState} from 'react';
import {Brand} from './brand';
export function WorkspaceNavigation({user,demo,active,title,open,onToggle,onNavigate,onLogout}:{user:{name:string;email:string;picture?:string|null;isOwner?:boolean};demo:boolean;active:string;title?:string;open:boolean;onToggle:()=>void;onNavigate:(page:string)=>void;onLogout:()=>void}) {
 const [accountOpen,setAccountOpen]=useState(false);
 const container=useRef<HTMLDivElement>(null), trigger=useRef<HTMLButtonElement>(null);
 useEffect(()=>{if(!accountOpen)return;const click=(e:PointerEvent)=>{if(!container.current?.contains(e.target as Node))setAccountOpen(false);};const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){setAccountOpen(false);trigger.current?.focus();}};document.addEventListener('pointerdown',click);document.addEventListener('keydown',key);return()=>{document.removeEventListener('pointerdown',click);document.removeEventListener('keydown',key);};},[accountOpen]);
 return <header className="workspace-navigation"><button className="brand-home" aria-label="TraderGym 持倉總覽" onClick={()=>onNavigate('overview')}><Brand/></button><span className="mobile-page-title">{title || active}</span><nav id="primary-navigation" className={open?'is-open':''} aria-label="主要導覽">{[['overview','持倉總覽'],['cycles','交易複盤'],['performance','績效回顧'],['trades','成交與資金'],...(!demo?[['ledgers','帳本與備份']]:[])].map(([key,label])=><button key={key} type="button" aria-current={active===key?'page':undefined} onClick={()=>onNavigate(key==='cycles'?'training':key)}>{label}</button>)}<div className="mobile-account-actions"><strong>{demo?"訪客練習":user.name}</strong><span>{demo?"離開後重置":user.email}</span>{!demo&&<a href="/settings">帳號設定</a>}{!demo&&user.isOwner&&<a href="/admin">管理後台</a>}<button onClick={onLogout}>{demo?"離開體驗":"登出"}</button></div></nav><div className="workspace-account" ref={container}><button ref={trigger} className="account-trigger" aria-label={`${demo?"訪客練習":user.name}，帳號選單`} aria-expanded={accountOpen} aria-controls="workspace-account-options" onClick={()=>setAccountOpen(v=>!v)}>{user.picture&&!demo?<img src={user.picture} alt="" width="32" height="32" referrerPolicy="no-referrer"/>:<span className="account-avatar" aria-hidden="true">{demo?'TG':user.name.slice(0,1)}</span>}<span>{demo?'訪客練習':user.name}</span><svg width="12" height="12" viewBox="0 0 12 12" aria-hidden="true"><path d="m3 4 3 3 3-3" fill="none" stroke="currentColor" strokeWidth="1.5"/></svg></button>{accountOpen&&<div id="workspace-account-options" className="account-options"><span>{demo?'離開後重置':user.email}</span>{!demo&&<a href="/settings">帳號設定</a>}{!demo&&user.isOwner&&<a href="/admin">管理後台</a>}<button onClick={onLogout}>{demo?'離開體驗':'登出'}</button></div>}</div><button className="navigation-toggle" aria-label={open?'收合導覽':'展開導覽'} aria-expanded={open} aria-controls="primary-navigation" onClick={onToggle}><svg viewBox="0 0 24 24" width="24" height="24" aria-hidden="true"><path d={open?'m6 6 12 12M6 18 18 6':'M4 6h16M4 12h16M4 18h16'} fill="none" stroke="currentColor" strokeWidth="2"/></svg></button></header>;
}
